// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.

//! Windows code pages for the charsets outside the standard.

use crate::code_page::CodePage;
// A group may have no Windows code pages of its own.
#[allow(unused_imports)]
use crate::extra_encodings as x;

/// Sorted by number, for binary search.
pub static EXTRA_CODE_PAGES: &[CodePage] = &[
    #[cfg(feature = "ebcdic")]
    CodePage {
        number: 37,
        encoding: &x::IBM037_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 437,
        encoding: &x::IBM437_INIT,
        canonical: true,
    },
    #[cfg(feature = "ebcdic")]
    CodePage {
        number: 500,
        encoding: &x::IBM500_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 737,
        encoding: &x::IBM737_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 775,
        encoding: &x::IBM775_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 850,
        encoding: &x::IBM850_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 852,
        encoding: &x::IBM852_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 855,
        encoding: &x::IBM855_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 857,
        encoding: &x::IBM857_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 860,
        encoding: &x::IBM860_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 861,
        encoding: &x::IBM861_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 862,
        encoding: &x::IBM862_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 863,
        encoding: &x::IBM863_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 864,
        encoding: &x::IBM864_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 865,
        encoding: &x::IBM865_INIT,
        canonical: true,
    },
    #[cfg(feature = "dos")]
    CodePage {
        number: 869,
        encoding: &x::IBM869_INIT,
        canonical: true,
    },
    #[cfg(feature = "ebcdic")]
    CodePage {
        number: 875,
        encoding: &x::IBM875_INIT,
        canonical: true,
    },
    #[cfg(feature = "ebcdic")]
    CodePage {
        number: 1026,
        encoding: &x::IBM1026_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10004,
        encoding: &x::X_MAC_ARABIC_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10006,
        encoding: &x::X_MAC_GREEK_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10010,
        encoding: &x::X_MAC_ROMANIAN_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10029,
        encoding: &x::X_MAC_CENTRALEURROMAN_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10079,
        encoding: &x::X_MAC_ICELANDIC_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10081,
        encoding: &x::X_MAC_TURKISH_INIT,
        canonical: true,
    },
    #[cfg(feature = "mac")]
    CodePage {
        number: 10082,
        encoding: &x::X_MAC_CROATIAN_INIT,
        canonical: true,
    },
    #[cfg(feature = "unicode-extras")]
    CodePage {
        number: 12000,
        encoding: &x::UTF_32LE_INIT,
        canonical: true,
    },
    #[cfg(feature = "unicode-extras")]
    CodePage {
        number: 12001,
        encoding: &x::UTF_32BE_INIT,
        canonical: true,
    },
    CodePage {
        number: 20127,
        encoding: &x::US_ASCII_INIT,
        canonical: true,
    },
    #[cfg(feature = "ebcdic")]
    CodePage {
        number: 20424,
        encoding: &x::IBM424_INIT,
        canonical: true,
    },
    CodePage {
        number: 28591,
        encoding: &x::ISO_8859_1_INIT,
        canonical: true,
    },
    #[cfg(feature = "single-byte")]
    CodePage {
        number: 28599,
        encoding: &x::ISO_8859_9_INIT,
        canonical: true,
    },
    #[cfg(feature = "unicode-extras")]
    CodePage {
        number: 65000,
        encoding: &x::UTF_7_INIT,
        canonical: true,
    },
];
