// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.

//! Static index tables derived from the WHATWG Encoding Standard.
//!
//! Each module is gated on the feature that asks for its encodings, so a build
//! that wants only, say, Shift_JIS carries none of the Chinese or Korean data.

#[cfg(feature = "big5")]
pub mod big5;
#[cfg(feature = "big5")]
pub mod big5_1984;
#[cfg(feature = "iso-2022-cn")]
pub mod cns11643;
#[cfg(feature = "euc-kr")]
pub mod euc_kr;
#[cfg(any(
    feature = "dos",
    feature = "ebcdic",
    feature = "mac",
    feature = "misc",
    feature = "single-byte"
))]
pub mod extra;
pub mod extra_labels;
#[cfg(feature = "gb18030")]
pub mod gb18030;
#[cfg(feature = "gb18030")]
pub mod gb2312;
#[cfg(any(feature = "euc-jp", feature = "iso-2022-jp", feature = "shift-jis"))]
pub mod jis;
#[cfg(any(feature = "euc-jp", feature = "iso-2022-jp", feature = "shift-jis"))]
pub mod jis0208_1997;
pub mod labels;
#[cfg(feature = "single-byte")]
pub mod single_byte;
#[cfg(feature = "translit")]
pub mod translit;
