// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.

//! Static index tables derived from the WHATWG Encoding Standard.

pub mod big5;
pub mod euc_kr;
pub mod gb18030;
pub mod jis;
pub mod labels;
pub mod single_byte;
