#!/usr/bin/env python3
"""Generate the static index tables in src/tables/ from the WHATWG Encoding Standard data.

Usage:  python3 tools/generate_tables.py [--offline]

Reads the upstream index data from tools/data/, downloading it there first if it is
missing, and writes the generated Rust sources into src/tables/.  Both the data and
the generated sources are checked in, so building the crate needs neither this
script nor a network connection.  Re-run it only to pick up upstream changes.
"""

import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(HERE, "data")
OUT = os.path.join(ROOT, "src", "tables")

INDEXES_URL = "https://encoding.spec.whatwg.org/indexes.json"
ENCODINGS_URL = "https://encoding.spec.whatwg.org/encodings.json"

HEADER = """\
// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.
"""


def fetch(url, name):
    """Reads the checked-in copy of an upstream resource, downloading it if absent.

    The copies live in tools/data/ so that regenerating is deterministic and works
    offline.  Delete one and re-run to pick up upstream changes."""
    os.makedirs(DATA, exist_ok=True)
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        if "--offline" in sys.argv:
            sys.exit("missing {} and --offline was given".format(path))
        with urllib.request.urlopen(url) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, "rb") as f:
        return json.loads(f.read())


def rows(values, per_line, fmt):
    out = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        out.append("    " + " ".join(fmt(v) + "," for v in chunk))
    return "\n".join(out)


def u16_hex(v):
    return "0x{:04X}".format(v)


def u32_hex(v):
    return "0x{:04X}".format(v)


def decode_table(name, index, width):
    """A pointer-indexed decode table.  0 means "no code point at this pointer"."""
    values = [0 if v is None else v for v in index]
    assert all(v <= 0xFFFF for v in values) or width == 32
    ty = "u16" if width == 16 else "u32"
    per = 16 if width == 16 else 12
    body = rows(values, per, u16_hex if width == 16 else u32_hex)
    return "#[rustfmt::skip]\npub static {}: [{}; {}] = [\n{}\n];\n".format(
        name, ty, len(values), body)


def encode_table(name, pairs, cp_width, gate=None):
    """Two parallel arrays sorted by code point, for binary search by the encoders.

    `gate` repeats the caller's `#[cfg(...)]` on the second array, since an
    attribute written above the call only covers the first."""
    cps = [cp for cp, _ in pairs]
    ptrs = [p for _, p in pairs]
    assert cps == sorted(cps)
    assert all(p <= 0xFFFF for p in ptrs)
    cp_ty = "u16" if cp_width == 16 else "u32"
    second = "#[cfg({})]\n".format(gate) if gate else ""
    out = "#[rustfmt::skip]\npub static {}_CODE_POINTS: [{}; {}] = [\n{}\n];\n\n".format(
        name, cp_ty, len(cps), rows(cps, 16 if cp_width == 16 else 12, u32_hex))
    out += "{}#[rustfmt::skip]\npub static {}_POINTERS: [u16; {}] = [\n{}\n];\n".format(
        second, name, len(ptrs), rows(ptrs, 16, u16_hex))
    return out


def first_pointers(index, skip=None):
    """`index pointer for code point`: the first pointer for each code point."""
    seen = {}
    for pointer, cp in enumerate(index):
        if cp is None:
            continue
        if skip is not None and skip(pointer):
            continue
        if cp not in seen:
            seen[cp] = pointer
    return sorted(seen.items())


def big5_pointers(index):
    """`index Big5 pointer`: skips the HKSCS extensions, and prefers the *last*
    pointer for six code points that would otherwise round-trip to an extension."""
    last = {0x2550, 0x255E, 0x2561, 0x256A, 0x5341, 0x5345}
    lowest = (0xA1 - 0x81) * 157
    seen = {}
    for pointer, cp in enumerate(index):
        if cp is None or pointer < lowest:
            continue
        if cp in last or cp not in seen:
            seen[cp] = pointer
    return sorted(seen.items())


# Names as they appear in indexes.json, mapped to the Rust identifier we expose.
SINGLE_BYTE = [
    ("ibm866", "IBM866"),
    ("iso-8859-2", "ISO_8859_2"),
    ("iso-8859-3", "ISO_8859_3"),
    ("iso-8859-4", "ISO_8859_4"),
    ("iso-8859-5", "ISO_8859_5"),
    ("iso-8859-6", "ISO_8859_6"),
    ("iso-8859-7", "ISO_8859_7"),
    ("iso-8859-8", "ISO_8859_8"),
    ("iso-8859-10", "ISO_8859_10"),
    ("iso-8859-13", "ISO_8859_13"),
    ("iso-8859-14", "ISO_8859_14"),
    ("iso-8859-15", "ISO_8859_15"),
    ("iso-8859-16", "ISO_8859_16"),
    ("koi8-r", "KOI8_R"),
    ("koi8-u", "KOI8_U"),
    ("macintosh", "MACINTOSH"),
    ("windows-874", "WINDOWS_874"),
    ("windows-1250", "WINDOWS_1250"),
    ("windows-1251", "WINDOWS_1251"),
    ("windows-1252", "WINDOWS_1252"),
    ("windows-1253", "WINDOWS_1253"),
    ("windows-1254", "WINDOWS_1254"),
    ("windows-1255", "WINDOWS_1255"),
    ("windows-1256", "WINDOWS_1256"),
    ("windows-1257", "WINDOWS_1257"),
    ("windows-1258", "WINDOWS_1258"),
    ("x-mac-cyrillic", "X_MAC_CYRILLIC"),
]

# WHATWG encoding name -> the `VariantEncoding` arm implementing it.  The
# single-byte encodings are absent; they all share `VariantEncoding::SingleByte`.
VARIANTS = {
    "UTF-8": "Utf8",
    "GBK": "Gb18030 { is_gbk: true }",
    "gb18030": "Gb18030 { is_gbk: false }",
    "Big5": "Big5",
    "EUC-JP": "EucJp",
    "ISO-2022-JP": "Iso2022Jp",
    "Shift_JIS": "ShiftJis",
    "EUC-KR": "EucKr",
    "replacement": "Replacement",
    "UTF-16BE": "Utf16Be",
    "UTF-16LE": "Utf16Le",
    "x-user-defined": "XUserDefined",
}

# The one-line doc on each public static; anything absent gets its own name.
ENCODING_DOCS = {
    "UTF-8": "UTF-8, the encoding every new format should use.",
    "ISO-8859-8-I": "ISO-8859-8-I, identical to [`ISO_8859_8`] except in its name and implied text direction.",
    "GBK": "GBK, which decodes as [`GB18030`] but whose encoder emits only two-byte sequences.",
    "gb18030": "gb18030, the Chinese national standard, which covers all of Unicode.",
    "replacement": "The `replacement` encoding, which decodes any non-empty input to a single U+FFFD.",
    "UTF-16BE": "UTF-16BE.  Decode only; encoding to it yields UTF-8, per `get an output encoding`.",
    "UTF-16LE": "UTF-16LE.  Decode only; encoding to it yields UTF-8, per `get an output encoding`.",
    "x-user-defined": "x-user-defined, which maps bytes 0x80 to 0xFF into the private use area.",
    "Big5": "Big5, with the Hong Kong Supplementary Character Set extensions.",
    "EUC-JP": "EUC-JP.  Its decoder also accepts JIS X 0212 via the 0x8F prefix.",
    "ISO-2022-JP": "ISO-2022-JP, the only stateful encoding in the standard.",
    "Shift_JIS": "Shift_JIS, including the Windows end-user defined character range.",
    "EUC-KR": "EUC-KR, in practice the Unified Hangul Code (Windows codepage 949).",
}

# WHATWG encoding name -> the Cargo feature its tables live behind.  `None` means
# the encoding needs no tables and is always present.
FEATURES = {
    "UTF-8": None,
    "UTF-16BE": None,
    "UTF-16LE": None,
    "replacement": None,
    "x-user-defined": None,
    "GBK": "gb18030",
    "gb18030": "gb18030",
    "Big5": "big5",
    "EUC-JP": "euc-jp",
    "ISO-2022-JP": "iso-2022-jp",
    "Shift_JIS": "shift-jis",
    "EUC-KR": "euc-kr",
    # Everything else is one of the 28 legacy single-byte encodings.
}


def feature(name):
    return FEATURES.get(name, "single-byte")


def cfg(name):
    """The `#[cfg(...)]` line gating `name`, or an empty string if always on."""
    f = feature(name)
    return "" if f is None else '#[cfg(feature = "{}")]\n'.format(f)


# WHATWG encoding name -> the Rust `Encoding` constant in `crate::encodings`.
CONST_NAMES = {
    "UTF-8": "UTF_8_INIT",
    "IBM866": "IBM866_INIT",
    "ISO-8859-2": "ISO_8859_2_INIT",
    "ISO-8859-3": "ISO_8859_3_INIT",
    "ISO-8859-4": "ISO_8859_4_INIT",
    "ISO-8859-5": "ISO_8859_5_INIT",
    "ISO-8859-6": "ISO_8859_6_INIT",
    "ISO-8859-7": "ISO_8859_7_INIT",
    "ISO-8859-8": "ISO_8859_8_INIT",
    "ISO-8859-8-I": "ISO_8859_8_I_INIT",
    "ISO-8859-10": "ISO_8859_10_INIT",
    "ISO-8859-13": "ISO_8859_13_INIT",
    "ISO-8859-14": "ISO_8859_14_INIT",
    "ISO-8859-15": "ISO_8859_15_INIT",
    "ISO-8859-16": "ISO_8859_16_INIT",
    "KOI8-R": "KOI8_R_INIT",
    "KOI8-U": "KOI8_U_INIT",
    "macintosh": "MACINTOSH_INIT",
    "windows-874": "WINDOWS_874_INIT",
    "windows-1250": "WINDOWS_1250_INIT",
    "windows-1251": "WINDOWS_1251_INIT",
    "windows-1252": "WINDOWS_1252_INIT",
    "windows-1253": "WINDOWS_1253_INIT",
    "windows-1254": "WINDOWS_1254_INIT",
    "windows-1255": "WINDOWS_1255_INIT",
    "windows-1256": "WINDOWS_1256_INIT",
    "windows-1257": "WINDOWS_1257_INIT",
    "windows-1258": "WINDOWS_1258_INIT",
    "x-mac-cyrillic": "X_MAC_CYRILLIC_INIT",
    "GBK": "GBK_INIT",
    "gb18030": "GB18030_INIT",
    "Big5": "BIG5_INIT",
    "EUC-JP": "EUC_JP_INIT",
    "ISO-2022-JP": "ISO_2022_JP_INIT",
    "Shift_JIS": "SHIFT_JIS_INIT",
    "EUC-KR": "EUC_KR_INIT",
    "replacement": "REPLACEMENT_INIT",
    "UTF-16BE": "UTF_16BE_INIT",
    "UTF-16LE": "UTF_16LE_INIT",
    "x-user-defined": "X_USER_DEFINED_INIT",
}



# --- charsets outside the Encoding Standard ---------------------------------
#
# Mapping data comes from the Unicode Consortium's MAPPINGS archive, whose files
# are checked in under tools/data/mappings/.  `full` marks a charset whose bytes
# below 0x80 are not plain ASCII, which needs a 256-entry table rather than the
# 128-entry one the standard's single-byte encodings use.
#
# (group, name, ident, mapping file, Windows code page or None, labels, full)
EXTRA = [
    # IBM PC / OEM code pages.  437 and 874 are omitted: the standard already
    # has IBM866 and windows-874, and CP866 is byte-for-byte identical.
    ("dos", "IBM437", "IBM437", "CP437.TXT", 437,
     ["cp437", "ibm437", "cspc8codepage437", "oem-us"], False),
    ("dos", "IBM737", "IBM737", "CP737.TXT", 737, ["cp737", "ibm737"], False),
    ("dos", "IBM775", "IBM775", "CP775.TXT", 775,
     ["cp775", "ibm775", "cspc775baltic"], False),
    ("dos", "IBM850", "IBM850", "CP850.TXT", 850,
     ["cp850", "ibm850", "cspc850multilingual"], False),
    ("dos", "IBM852", "IBM852", "CP852.TXT", 852, ["cp852", "ibm852", "cspcp852"], False),
    ("dos", "IBM855", "IBM855", "CP855.TXT", 855, ["cp855", "ibm855", "csibm855"], False),
    ("dos", "IBM856", "IBM856", "CP856.TXT", None, ["cp856", "ibm856"], False),
    ("dos", "IBM857", "IBM857", "CP857.TXT", 857, ["cp857", "ibm857", "csibm857"], False),
    ("dos", "IBM860", "IBM860", "CP860.TXT", 860, ["cp860", "ibm860", "csibm860"], False),
    ("dos", "IBM861", "IBM861", "CP861.TXT", 861,
     ["cp861", "ibm861", "cp-is", "csibm861"], False),
    ("dos", "IBM862", "IBM862", "CP862.TXT", 862,
     ["cp862", "ibm862", "dos-862", "cspc862latinhebrew"], False),
    ("dos", "IBM863", "IBM863", "CP863.TXT", 863, ["cp863", "ibm863", "csibm863"], False),
    ("dos", "IBM864", "IBM864", "CP864.TXT", 864, ["cp864", "ibm864", "csibm864"], True),
    ("dos", "IBM865", "IBM865", "CP865.TXT", 865, ["cp865", "ibm865", "csibm865"], False),
    ("dos", "IBM869", "IBM869", "CP869.TXT", 869,
     ["cp869", "ibm869", "cp-gr", "csibm869"], False),
    ("dos", "IBM1006", "IBM1006", "CP1006.TXT", None, ["cp1006", "ibm1006"], False),

    # Apple's regional variants.  Mac OS Roman and Mac OS Cyrillic are the
    # standard's `macintosh` and `x-mac-cyrillic`; Hebrew and Thai are omitted
    # because Apple maps some of their bytes to two code points.
    ("mac", "x-mac-arabic", "X_MAC_ARABIC", "ARABIC.TXT", 10004,
     ["x-mac-arabic", "mac-arabic"], False),
    ("mac", "x-mac-celtic", "X_MAC_CELTIC", "CELTIC.TXT", None,
     ["x-mac-celtic", "mac-celtic"], False),
    ("mac", "x-mac-centraleurroman", "X_MAC_CENTRALEURROMAN", "CENTEURO.TXT", 10029,
     ["x-mac-centraleurroman", "mac-centraleurroman", "x-mac-ce"], False),
    ("mac", "x-mac-croatian", "X_MAC_CROATIAN", "CROATIAN.TXT", 10082,
     ["x-mac-croatian", "mac-croatian"], False),
    ("mac", "x-mac-farsi", "X_MAC_FARSI", "FARSI.TXT", None,
     ["x-mac-farsi", "mac-farsi"], False),
    ("mac", "x-mac-gaelic", "X_MAC_GAELIC", "GAELIC.TXT", None,
     ["x-mac-gaelic", "mac-gaelic"], False),
    ("mac", "x-mac-greek", "X_MAC_GREEK", "GREEK.TXT", 10006,
     ["x-mac-greek", "mac-greek"], False),
    ("mac", "x-mac-icelandic", "X_MAC_ICELANDIC", "ICELAND.TXT", 10079,
     ["x-mac-icelandic", "mac-icelandic"], False),
    ("mac", "x-mac-romanian", "X_MAC_ROMANIAN", "ROMANIAN.TXT", 10010,
     ["x-mac-romanian", "mac-romanian"], False),
    ("mac", "x-mac-turkish", "X_MAC_TURKISH", "TURKISH.TXT", 10081,
     ["x-mac-turkish", "mac-turkish"], False),

    # IBM mainframe EBCDIC.  These permute the whole byte range.
    ("ebcdic", "IBM037", "IBM037", "CP037.TXT", 37,
     ["cp037", "ibm037", "ebcdic-cp-us", "ebcdic-cp-ca", "ebcdic-cp-wt",
      "ebcdic-cp-nl", "csibm037"], True),
    ("ebcdic", "IBM424", "IBM424", "CP424.TXT", 20424,
     ["cp424", "ibm424", "ebcdic-cp-he", "csibm424"], True),
    ("ebcdic", "IBM500", "IBM500", "CP500.TXT", 500,
     ["cp500", "ibm500", "ebcdic-cp-be", "ebcdic-cp-ch", "csibm500"], True),
    ("ebcdic", "IBM875", "IBM875", "CP875.TXT", 875, ["cp875", "ibm875"], True),
    ("ebcdic", "IBM1026", "IBM1026", "CP1026.TXT", 1026,
     ["cp1026", "ibm1026", "csibm1026"], True),

    # Everything else.
    ("misc", "Atari-ST", "ATARI_ST", "ATARIST.TXT", None, ["atari-st", "atarist"], False),
    ("misc", "KZ-1048", "KZ_1048", "KZ1048.TXT", None,
     ["kz-1048", "kz1048", "strk1048-2002", "rk1048", "cskz1048"], False),
]

MAPPINGS = os.path.join(HERE, "data", "mappings")


def load_mapping(filename):
    """Parses a Unicode MAPPINGS file into a 256-entry byte -> code point table."""
    table = [None] * 256
    with open(os.path.join(MAPPINGS, filename), encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            if not parts[0].lower().startswith("0x") or not parts[1].lower().startswith("0x"):
                continue
            assert "+" not in parts[1], "{}: multi-code-point mapping".format(filename)
            byte = int(parts[0], 16)
            if byte < 256:
                table[byte] = int(parts[1], 16)
    return table



def emit_extra(indexes):
    """Writes the tables, `Encoding`s, labels and code pages for EXTRA."""
    groups = sorted({g for g, *_ in EXTRA})
    parts = [HEADER, """
//! Tables for the charsets outside the WHATWG Encoding Standard.
//!
//! Generated from the Unicode Consortium's MAPPINGS archive.  A `_DECODE` table
//! holding 128 entries covers bytes 0x80 to 0xFF, with 0 for an unmapped byte;
//! one holding 256 entries covers every byte, with 0xFFFF for an unmapped one,
//! because those charsets map a byte to U+0000.

"""]
    used_labels = set()
    code_pages = []
    for group, name, ident, filename, cp, labels, full in EXTRA:
        table = load_mapping(filename)
        gate = '#[cfg(feature = "{}")]\n'.format(group)
        if full:
            values = [0xFFFF if v is None else v for v in table]
            assert all(v <= 0xFFFF for v in values), name
            assert 0xFFFF not in [v for v in table if v is not None], name
            parts.append("\n/// {} ({})\n".format(name, filename))
            parts.append(gate)
            parts.append("#[rustfmt::skip]\npub static {}_DECODE: [u16; 256] = [\n{}\n];\n".format(
                ident, rows(values, 12, u16_hex)))
            pairs = sorted({v: b for b, v in reversed(list(enumerate(table))) if v is not None}.items())
        else:
            for b in range(0x80):
                assert table[b] in (None, b), "{}: byte {:#04x} is not ASCII".format(name, b)
            values = [0 if table[b] is None else table[b] for b in range(0x80, 0x100)]
            assert 0 not in [v for v in table[0x80:] if v is not None], name
            parts.append("\n/// {} ({})\n".format(name, filename))
            parts.append(gate)
            parts.append("#[rustfmt::skip]\npub static {}_DECODE: [u16; 128] = [\n{}\n];\n".format(
                ident, rows(values, 12, u16_hex)))
            pairs = sorted({v: b for b, v in reversed(list(enumerate(table)))
                            if v is not None and b >= 0x80}.items())
        cps = [cp_ for cp_, _ in pairs]
        bytes_ = [b for _, b in pairs]
        parts.append(gate)
        parts.append("#[rustfmt::skip]\npub static {}_ENCODE_CODE_POINTS: [u16; {}] = [\n{}\n];\n".format(
            ident, len(cps), rows(cps, 12, u16_hex)))
        parts.append(gate)
        parts.append("#[rustfmt::skip]\npub static {}_ENCODE_BYTES: [u8; {}] = [\n{}\n];\n".format(
            ident, len(bytes_), rows(bytes_, 16, lambda v: "0x{:02X}".format(v))))
        for label in labels:
            assert label not in used_labels, "duplicate label " + label
            used_labels.add(label)
        if cp is not None:
            code_pages.append((cp, ident, group))
    write(os.path.join(OUT, "extra.rs"), "".join(parts))

    # The Encoding constants and statics.
    parts = [HEADER, """
//! The [`Encoding`] instances for the charsets outside the standard.

use crate::Encoding;
use crate::tables::extra as t;
use crate::variant::VariantEncoding;
"""]
    for group in groups:
        parts.append("\n// {}\n".format(GROUP_DOCS[group]))
        for g, name, ident, _f, _cp, _labels, full in EXTRA:
            if g != group:
                continue
            arm = "FullByte" if full else "SingleByte"
            parts.append(
                '\n#[cfg(feature = "{g}")]\npub(crate) const {i}_INIT: Encoding = Encoding::new(\n'
                '    "{n}",\n    VariantEncoding::{arm}(\n        &t::{i}_DECODE,\n'
                '        &t::{i}_ENCODE_CODE_POINTS,\n        &t::{i}_ENCODE_BYTES,\n    ),\n);\n'
                .format(g=g, i=ident, n=name, arm=arm))
            parts.append('/// {n}\n#[cfg(feature = "{g}")]\npub static {i}: &Encoding = &{i}_INIT;\n'
                         .format(g=g, i=ident, n=name))
    write(os.path.join(ROOT, "src", "extra_encodings.rs"), "".join(parts))

    # Labels and code pages, merged into the tables the lookups read.
    label_rows = sorted((l, ident, group)
                        for group, _n, ident, _f, _cp, labels, _full in EXTRA
                        for l in labels)
    parts = [HEADER, """
//! Windows code pages for the charsets outside the standard.

use crate::code_page::CodePage;
// A group may have no Windows code pages of its own.
#[cfg(any(feature = "dos", feature = "ebcdic", feature = "mac", feature = "misc"))]
#[allow(unused_imports)]
use crate::extra_encodings as x;
"""]
    parts.append("")
    parts.append("\n/// Sorted by number, for binary search.\n")
    parts.append("pub static EXTRA_CODE_PAGES: &[CodePage] = &[\n")
    for cp, ident, group in sorted(code_pages):
        parts.append('    #[cfg(feature = "{}")]\n    CodePage {{ number: {}, encoding: &x::{}_INIT, canonical: true }},\n'
                     .format(group, cp, ident))
    parts.append("];\n")
    write(os.path.join(OUT, "extra_labels.rs"), "".join(parts))
    return label_rows


GROUP_DOCS = {
    "dos": "IBM PC / OEM code pages",
    "mac": "Apple's regional variants of Mac OS Roman",
    "ebcdic": "IBM mainframe EBCDIC code pages",
    "misc": "Everything else",
}


def write(path, text):
    with open(path, "w", newline="\n") as f:
        f.write(text)
    print("wrote {} ({} bytes)".format(os.path.relpath(path, ROOT), len(text)))


def main():
    indexes = fetch(INDEXES_URL, "indexes.json")
    encodings = fetch(ENCODINGS_URL, "encodings.json")
    os.makedirs(OUT, exist_ok=True)

    # --- single-byte -----------------------------------------------------
    parts = [HEADER, "\n//! Decode and encode tables for the legacy single-byte encodings.\n"]
    for json_name, rust_name in SINGLE_BYTE:
        index = indexes[json_name]
        assert len(index) == 128
        parts.append("\n/// index {}\n".format(json_name))
        parts.append(decode_table(rust_name + "_DECODE", index, 16))
        pairs = first_pointers(index)
        cps = [cp for cp, _ in pairs]
        ptrs = [p for _, p in pairs]
        parts.append("\n#[rustfmt::skip]\npub static {}_ENCODE_CODE_POINTS: [u16; {}] = [\n{}\n];\n".format(
            rust_name, len(cps), rows(cps, 16, u16_hex)))
        parts.append("\n#[rustfmt::skip]\npub static {}_ENCODE_BYTES: [u8; {}] = [\n{}\n];\n".format(
            rust_name, len(ptrs), rows([p + 0x80 for p in ptrs], 16, lambda v: "0x{:02X}".format(v))))
    write(os.path.join(OUT, "single_byte.rs"), "".join(parts))

    # --- big5 ------------------------------------------------------------
    big5 = indexes["big5"]
    parts = [HEADER, "\n//! index Big5.\n\n"]
    parts.append(decode_table("BIG5_DECODE", big5, 32))
    parts.append("\n")
    parts.append(encode_table("BIG5_ENCODE", big5_pointers(big5), 32))
    write(os.path.join(OUT, "big5.rs"), "".join(parts))

    # --- gb18030 ---------------------------------------------------------
    gb = indexes["gb18030"]
    parts = [HEADER, "\n//! index gb18030 and index gb18030 ranges.\n\n"]
    parts.append(decode_table("GB18030_DECODE", gb, 16))
    parts.append("\n")
    parts.append(encode_table("GB18030_ENCODE", first_pointers(gb), 16))
    ranges = indexes["gb18030-ranges"]
    parts.append("\n/// index gb18030 ranges: (pointer, code point) pairs, sorted by both.\n")
    parts.append("#[rustfmt::skip]\npub static GB18030_RANGES: [(u32, u32); {}] = [\n{}\n];\n".format(
        len(ranges),
        "\n".join("    (0x{:05X}, 0x{:05X}),".format(p, c) for p, c in ranges)))
    write(os.path.join(OUT, "gb18030.rs"), "".join(parts))

    # --- jis0208 / jis0212 / iso-2022-jp katakana ------------------------
    jis0208 = indexes["jis0208"]
    jis0212 = indexes["jis0212"]
    katakana = indexes["iso-2022-jp-katakana"]
    # Three encodings share index jis0208, so each static is gated on exactly
    # the features that read it.
    jp = 'feature = "iso-2022-jp"'
    ej = 'feature = "euc-jp"'
    sj = 'feature = "shift-jis"'
    parts = [HEADER, "\n//! index jis0208, index jis0212 and index ISO-2022-JP katakana.\n\n"]
    parts.append(decode_table("JIS0208_DECODE", jis0208, 16))
    parts.append("\n/// Read only by EUC-JP, through the 0x8F prefix.\n")
    parts.append("#[cfg({})]\n".format(ej))
    parts.append(decode_table("JIS0212_DECODE", jis0212, 16))
    parts.append("\n/// `index pointer for code point in index jis0208`, used by EUC-JP and ISO-2022-JP.\n")
    parts.append("#[cfg(any({}, {}))]\n".format(ej, jp))
    parts.append(encode_table("JIS0208_ENCODE", first_pointers(jis0208), 16, gate="any({}, {})".format(ej, jp)))
    parts.append("\n/// `index Shift_JIS pointer`: index jis0208 without pointers 8272..=8835.\n")
    parts.append("#[cfg({})]\n".format(sj))
    parts.append(encode_table(
        "SHIFT_JIS_ENCODE",
        first_pointers(jis0208, skip=lambda p: 8272 <= p <= 8835),
        16,
        gate=sj))
    parts.append("\n/// index ISO-2022-JP katakana, indexed by `code point - 0xFF61`.\n")
    parts.append("#[cfg({})]\n".format(jp))
    parts.append("#[rustfmt::skip]\npub static ISO_2022_JP_KATAKANA: [u16; {}] = [\n{}\n];\n".format(
        len(katakana), rows(katakana, 16, u16_hex)))
    write(os.path.join(OUT, "jis.rs"), "".join(parts))

    # --- euc-kr ----------------------------------------------------------
    euckr = indexes["euc-kr"]
    parts = [HEADER, "\n//! index EUC-KR.\n\n"]
    parts.append(decode_table("EUC_KR_DECODE", euckr, 16))
    parts.append("\n")
    parts.append(encode_table("EUC_KR_ENCODE", first_pointers(euckr), 16))
    write(os.path.join(OUT, "euc_kr.rs"), "".join(parts))

    # --- labels ----------------------------------------------------------
    extra_rows = emit_extra(indexes)
    labels = []
    names = []
    for group in encodings:
        for enc in group["encodings"]:
            names.append(enc["name"])
            for label in enc["labels"]:
                labels.append((label, CONST_NAMES[enc["name"]]))
    # Merge in the charsets outside the standard; the generator asserts below
    # that no label is claimed twice, in any feature combination.
    by_const = {CONST_NAMES[n]: n for n in names}
    all_labels = [(label, const, feature(by_const[const]), "e") for label, const in labels]
    all_labels += [(label, ident + "_INIT", group, "x") for label, ident, group in extra_rows]
    all_labels.sort(key=lambda r: r[0])
    assert len(set(r[0] for r in all_labels)) == len(all_labels), "duplicate label"
    parts = [HEADER, """
//! Every label the standard defines, sorted for binary search.
//!
//! An entry is present only when the encoding it names is compiled in, so the
//! table shrinks with the enabled table groups rather than pointing at
//! encodings that do not exist.

use crate::Encoding;
use crate::encodings as e;
#[cfg(any(feature = "dos", feature = "ebcdic", feature = "mac", feature = "misc"))]
use crate::extra_encodings as x;

/// Every label of every encoding compiled in, sorted for binary search.
///
/// Labels are already lowercase and trimmed; callers must normalize before
/// searching.  `whatwg` marks a label the Encoding Standard defines, which is
/// what lets the standard's own lookup refuse everything else.
pub struct Label {
    pub text: &'static str,
    pub encoding: &'static Encoding,
    pub whatwg: bool,
}

pub static LABELS: &[Label] = &[
"""]
    for label, const, group, module in all_labels:
        gate = "" if group is None else '    #[cfg(feature = "{}")]\n'.format(group)
        parts.append('{}    Label {{ text: "{}", encoding: &{}::{}, whatwg: {} }},\n'
                     .format(gate, label, module, const, "true" if module == "e" else "false"))
    parts.append("];\n\n")
    parts.append("/// Every encoding compiled in: the standard's first, then the rest.\n")
    parts.append("pub static ALL_ENCODINGS: &[&Encoding] = &[\n")
    for name in names:
        parts.append("    {}&e::{},\n".format(
            cfg(name).replace("\n", "\n    "), CONST_NAMES[name]))
    for group, _n, ident, _f, _cp, _l, _full in EXTRA:
        parts.append('    #[cfg(feature = "{}")]\n    &x::{}_INIT,\n'.format(group, ident))
    parts.append("];\n")
    write(os.path.join(OUT, "labels.rs"), "".join(parts))

    # --- the Encoding constants and statics ------------------------------
    # Encoding name -> the table identifier in tables::single_byte.
    sb_tables = {n: CONST_NAMES[n][: -len("_INIT")]
                 for n in names if feature(n) == "single-byte"}
    # ISO-8859-8-I shares its index with ISO-8859-8.
    sb_tables["ISO-8859-8-I"] = "ISO_8859_8"
    parts = [HEADER, """
//! The [`Encoding`] instances for every encoding compiled in.
//!
//! Each exists once as a private `const`, so that it can be named in other
//! constants such as the label table, and once as the `&'static` reference the
//! API hands out.  Both are gated on the feature that carries the encoding's
//! tables; see the crate documentation for what each feature covers.

use crate::Encoding;
#[cfg(feature = "single-byte")]
use crate::tables::single_byte as sb;
use crate::variant::VariantEncoding;
"""]
    for group in encodings:
        parts.append("\n// {}\n".format(group["heading"]))
        for enc in group["encodings"]:
            name = enc["name"]
            const = CONST_NAMES[name]
            if name in sb_tables:
                t = sb_tables[name]
                variant = ("VariantEncoding::SingleByte(\n"
                           "    &sb::{t}_DECODE,\n"
                           "    &sb::{t}_ENCODE_CODE_POINTS,\n"
                           "    &sb::{t}_ENCODE_BYTES,\n)").format(t=t)
            else:
                variant = "VariantEncoding::" + VARIANTS[name]
            doc = ENCODING_DOCS.get(name, "{}.".format(name))
            gate = cfg(name)
            parts.append('\n{}pub(crate) const {}: Encoding = Encoding::new("{}", {});\n'
                         .format(gate, const, name, variant))
            parts.append('/// {}\n{}pub static {}: &Encoding = &{};\n'
                         .format(doc, gate, const[:-len("_INIT")], const))
    write(os.path.join(ROOT, "src", "encodings.rs"), "".join(parts))

    # --- module root -----------------------------------------------------
    write(os.path.join(OUT, "mod.rs"), HEADER + """
//! Static index tables derived from the WHATWG Encoding Standard.
//!
//! Each module is gated on the feature that asks for its encodings, so a build
//! that wants only, say, Shift_JIS carries none of the Chinese or Korean data.

#[cfg(feature = "big5")]
pub mod big5;
#[cfg(feature = "euc-kr")]
pub mod euc_kr;
#[cfg(feature = "gb18030")]
pub mod gb18030;
#[cfg(any(feature = "euc-jp", feature = "iso-2022-jp", feature = "shift-jis"))]
pub mod jis;
#[cfg(any(feature = "dos", feature = "ebcdic", feature = "mac", feature = "misc"))]
pub mod extra;
pub mod extra_labels;
pub mod labels;
#[cfg(feature = "single-byte")]
pub mod single_byte;
""")


if __name__ == "__main__":
    main()
