#!/usr/bin/env python3
"""Generate the static index tables in src/tables/ from the WHATWG Encoding Standard data.

Usage:  python3 tools/generate_tables.py [--offline]

Downloads https://encoding.spec.whatwg.org/indexes.json and encodings.json (cached
next to this script under .cache/) and writes the generated Rust sources.  The
generated files are checked into the repository; this script only needs to be re-run
when the upstream indexes change.
"""

import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, ".cache")
OUT = os.path.join(ROOT, "src", "tables")

INDEXES_URL = "https://encoding.spec.whatwg.org/indexes.json"
ENCODINGS_URL = "https://encoding.spec.whatwg.org/encodings.json"

HEADER = """\
// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.
"""


def fetch(url, name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name)
    if not os.path.exists(path):
        if "--offline" in sys.argv:
            sys.exit("missing cache file {} and --offline was given".format(path))
        with urllib.request.urlopen(url) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, "rb") as f:
        return json.loads(f.read())


def rows(values, per_line, fmt):
    out = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        out.append("    " + " ".join(fmt(v) + "," for v in chunk))
    return "\n".join(out)


def u16_hex(v):
    return "0x{:04X}".format(v)


def u32_hex(v):
    return "0x{:04X}".format(v)


def decode_table(name, index, width):
    """A pointer-indexed decode table.  0 means "no code point at this pointer"."""
    values = [0 if v is None else v for v in index]
    assert all(v <= 0xFFFF for v in values) or width == 32
    ty = "u16" if width == 16 else "u32"
    per = 16 if width == 16 else 12
    body = rows(values, per, u16_hex if width == 16 else u32_hex)
    return "pub static {}: [{}; {}] = [\n{}\n];\n".format(name, ty, len(values), body)


def encode_table(name, pairs, cp_width):
    """Two parallel arrays sorted by code point, for binary search by the encoders."""
    cps = [cp for cp, _ in pairs]
    ptrs = [p for _, p in pairs]
    assert cps == sorted(cps)
    assert all(p <= 0xFFFF for p in ptrs)
    cp_ty = "u16" if cp_width == 16 else "u32"
    out = "pub static {}_CODE_POINTS: [{}; {}] = [\n{}\n];\n\n".format(
        name, cp_ty, len(cps), rows(cps, 16 if cp_width == 16 else 12, u32_hex))
    out += "pub static {}_POINTERS: [u16; {}] = [\n{}\n];\n".format(
        name, len(ptrs), rows(ptrs, 16, u16_hex))
    return out


def first_pointers(index, skip=None):
    """`index pointer for code point`: the first pointer for each code point."""
    seen = {}
    for pointer, cp in enumerate(index):
        if cp is None:
            continue
        if skip is not None and skip(pointer):
            continue
        if cp not in seen:
            seen[cp] = pointer
    return sorted(seen.items())


def big5_pointers(index):
    """`index Big5 pointer`: skips the HKSCS extensions, and prefers the *last*
    pointer for six code points that would otherwise round-trip to an extension."""
    last = {0x2550, 0x255E, 0x2561, 0x256A, 0x5341, 0x5345}
    lowest = (0xA1 - 0x81) * 157
    seen = {}
    for pointer, cp in enumerate(index):
        if cp is None or pointer < lowest:
            continue
        if cp in last or cp not in seen:
            seen[cp] = pointer
    return sorted(seen.items())


# Names as they appear in indexes.json, mapped to the Rust identifier we expose.
SINGLE_BYTE = [
    ("ibm866", "IBM866"),
    ("iso-8859-2", "ISO_8859_2"),
    ("iso-8859-3", "ISO_8859_3"),
    ("iso-8859-4", "ISO_8859_4"),
    ("iso-8859-5", "ISO_8859_5"),
    ("iso-8859-6", "ISO_8859_6"),
    ("iso-8859-7", "ISO_8859_7"),
    ("iso-8859-8", "ISO_8859_8"),
    ("iso-8859-10", "ISO_8859_10"),
    ("iso-8859-13", "ISO_8859_13"),
    ("iso-8859-14", "ISO_8859_14"),
    ("iso-8859-15", "ISO_8859_15"),
    ("iso-8859-16", "ISO_8859_16"),
    ("koi8-r", "KOI8_R"),
    ("koi8-u", "KOI8_U"),
    ("macintosh", "MACINTOSH"),
    ("windows-874", "WINDOWS_874"),
    ("windows-1250", "WINDOWS_1250"),
    ("windows-1251", "WINDOWS_1251"),
    ("windows-1252", "WINDOWS_1252"),
    ("windows-1253", "WINDOWS_1253"),
    ("windows-1254", "WINDOWS_1254"),
    ("windows-1255", "WINDOWS_1255"),
    ("windows-1256", "WINDOWS_1256"),
    ("windows-1257", "WINDOWS_1257"),
    ("windows-1258", "WINDOWS_1258"),
    ("x-mac-cyrillic", "X_MAC_CYRILLIC"),
]

# WHATWG encoding name -> the Rust `Encoding` constant in `crate::encodings`.
CONST_NAMES = {
    "UTF-8": "UTF_8_INIT",
    "IBM866": "IBM866_INIT",
    "ISO-8859-2": "ISO_8859_2_INIT",
    "ISO-8859-3": "ISO_8859_3_INIT",
    "ISO-8859-4": "ISO_8859_4_INIT",
    "ISO-8859-5": "ISO_8859_5_INIT",
    "ISO-8859-6": "ISO_8859_6_INIT",
    "ISO-8859-7": "ISO_8859_7_INIT",
    "ISO-8859-8": "ISO_8859_8_INIT",
    "ISO-8859-8-I": "ISO_8859_8_I_INIT",
    "ISO-8859-10": "ISO_8859_10_INIT",
    "ISO-8859-13": "ISO_8859_13_INIT",
    "ISO-8859-14": "ISO_8859_14_INIT",
    "ISO-8859-15": "ISO_8859_15_INIT",
    "ISO-8859-16": "ISO_8859_16_INIT",
    "KOI8-R": "KOI8_R_INIT",
    "KOI8-U": "KOI8_U_INIT",
    "macintosh": "MACINTOSH_INIT",
    "windows-874": "WINDOWS_874_INIT",
    "windows-1250": "WINDOWS_1250_INIT",
    "windows-1251": "WINDOWS_1251_INIT",
    "windows-1252": "WINDOWS_1252_INIT",
    "windows-1253": "WINDOWS_1253_INIT",
    "windows-1254": "WINDOWS_1254_INIT",
    "windows-1255": "WINDOWS_1255_INIT",
    "windows-1256": "WINDOWS_1256_INIT",
    "windows-1257": "WINDOWS_1257_INIT",
    "windows-1258": "WINDOWS_1258_INIT",
    "x-mac-cyrillic": "X_MAC_CYRILLIC_INIT",
    "GBK": "GBK_INIT",
    "gb18030": "GB18030_INIT",
    "Big5": "BIG5_INIT",
    "EUC-JP": "EUC_JP_INIT",
    "ISO-2022-JP": "ISO_2022_JP_INIT",
    "Shift_JIS": "SHIFT_JIS_INIT",
    "EUC-KR": "EUC_KR_INIT",
    "replacement": "REPLACEMENT_INIT",
    "UTF-16BE": "UTF_16BE_INIT",
    "UTF-16LE": "UTF_16LE_INIT",
    "x-user-defined": "X_USER_DEFINED_INIT",
}


def write(path, text):
    with open(path, "w", newline="\n") as f:
        f.write(text)
    print("wrote {} ({} bytes)".format(os.path.relpath(path, ROOT), len(text)))


def main():
    indexes = fetch(INDEXES_URL, "indexes.json")
    encodings = fetch(ENCODINGS_URL, "encodings.json")
    os.makedirs(OUT, exist_ok=True)

    # --- single-byte -----------------------------------------------------
    parts = [HEADER, "\n//! Decode and encode tables for the legacy single-byte encodings.\n"]
    for json_name, rust_name in SINGLE_BYTE:
        index = indexes[json_name]
        assert len(index) == 128
        parts.append("\n/// index {}\n".format(json_name))
        parts.append(decode_table(rust_name + "_DECODE", index, 16))
        pairs = first_pointers(index)
        cps = [cp for cp, _ in pairs]
        ptrs = [p for _, p in pairs]
        parts.append("\npub static {}_ENCODE_CODE_POINTS: [u16; {}] = [\n{}\n];\n".format(
            rust_name, len(cps), rows(cps, 16, u16_hex)))
        parts.append("\npub static {}_ENCODE_BYTES: [u8; {}] = [\n{}\n];\n".format(
            rust_name, len(ptrs), rows([p + 0x80 for p in ptrs], 16, lambda v: "0x{:02X}".format(v))))
    write(os.path.join(OUT, "single_byte.rs"), "".join(parts))

    # --- big5 ------------------------------------------------------------
    big5 = indexes["big5"]
    parts = [HEADER, "\n//! index Big5.\n\n"]
    parts.append(decode_table("BIG5_DECODE", big5, 32))
    parts.append("\n")
    parts.append(encode_table("BIG5_ENCODE", big5_pointers(big5), 32))
    write(os.path.join(OUT, "big5.rs"), "".join(parts))

    # --- gb18030 ---------------------------------------------------------
    gb = indexes["gb18030"]
    parts = [HEADER, "\n//! index gb18030 and index gb18030 ranges.\n\n"]
    parts.append(decode_table("GB18030_DECODE", gb, 16))
    parts.append("\n")
    parts.append(encode_table("GB18030_ENCODE", first_pointers(gb), 16))
    ranges = indexes["gb18030-ranges"]
    parts.append("\n/// index gb18030 ranges: (pointer, code point) pairs, sorted by both.\n")
    parts.append("pub static GB18030_RANGES: [(u32, u32); {}] = [\n{}\n];\n".format(
        len(ranges),
        "\n".join("    (0x{:05X}, 0x{:05X}),".format(p, c) for p, c in ranges)))
    write(os.path.join(OUT, "gb18030.rs"), "".join(parts))

    # --- jis0208 / jis0212 / iso-2022-jp katakana ------------------------
    jis0208 = indexes["jis0208"]
    jis0212 = indexes["jis0212"]
    katakana = indexes["iso-2022-jp-katakana"]
    parts = [HEADER, "\n//! index jis0208, index jis0212 and index ISO-2022-JP katakana.\n\n"]
    parts.append(decode_table("JIS0208_DECODE", jis0208, 16))
    parts.append("\n")
    parts.append(decode_table("JIS0212_DECODE", jis0212, 16))
    parts.append("\n/// `index pointer for code point in index jis0208`, used by EUC-JP and ISO-2022-JP.\n")
    parts.append(encode_table("JIS0208_ENCODE", first_pointers(jis0208), 16))
    parts.append("\n/// `index Shift_JIS pointer`: index jis0208 without pointers 8272..=8835.\n")
    parts.append(encode_table(
        "SHIFT_JIS_ENCODE",
        first_pointers(jis0208, skip=lambda p: 8272 <= p <= 8835),
        16))
    parts.append("\n/// index ISO-2022-JP katakana, indexed by `code point - 0xFF61`.\n")
    parts.append("pub static ISO_2022_JP_KATAKANA: [u16; {}] = [\n{}\n];\n".format(
        len(katakana), rows(katakana, 16, u16_hex)))
    write(os.path.join(OUT, "jis.rs"), "".join(parts))

    # --- euc-kr ----------------------------------------------------------
    euckr = indexes["euc-kr"]
    parts = [HEADER, "\n//! index EUC-KR.\n\n"]
    parts.append(decode_table("EUC_KR_DECODE", euckr, 16))
    parts.append("\n")
    parts.append(encode_table("EUC_KR_ENCODE", first_pointers(euckr), 16))
    write(os.path.join(OUT, "euc_kr.rs"), "".join(parts))

    # --- labels ----------------------------------------------------------
    labels = []
    names = []
    for group in encodings:
        for enc in group["encodings"]:
            names.append(enc["name"])
            for label in enc["labels"]:
                labels.append((label, CONST_NAMES[enc["name"]]))
    labels.sort(key=lambda kv: kv[0])
    assert len(set(l for l, _ in labels)) == len(labels), "duplicate label"
    parts = [HEADER, """
//! Every label defined by the standard, sorted for binary search.

use crate::Encoding;
use crate::encodings as e;

/// `(label, encoding)` pairs, sorted by label.  Labels are already lowercase and
/// trimmed; callers must normalize before searching.
pub static LABELS: [(&str, &Encoding); %d] = [
""" % len(labels)]
    for label, const in labels:
        parts.append('    ("{}", &e::{}),\n'.format(label, const))
    parts.append("];\n\n")
    parts.append("/// Every encoding defined by the standard, in specification order.\n")
    parts.append("pub static ALL_ENCODINGS: [&Encoding; {}] = [\n".format(len(names)))
    for name in names:
        parts.append("    &e::{},\n".format(CONST_NAMES[name]))
    parts.append("];\n")
    write(os.path.join(OUT, "labels.rs"), "".join(parts))

    # --- module root -----------------------------------------------------
    write(os.path.join(OUT, "mod.rs"), HEADER + """
//! Static index tables derived from the WHATWG Encoding Standard.

pub mod big5;
pub mod euc_kr;
pub mod gb18030;
pub mod jis;
pub mod labels;
pub mod single_byte;
""")


if __name__ == "__main__":
    main()
