#!/usr/bin/env python3
"""Generate the static index tables in src/tables/ from the WHATWG Encoding Standard data.

Usage:  python3 tools/generate_tables.py [--offline]

Reads the upstream index data from tools/data/, downloading it there first if it is
missing, and writes the generated Rust sources into src/tables/.  Both the data and
the generated sources are checked in, so building the crate needs neither this
script nor a network connection.  Re-run it only to pick up upstream changes.
"""

import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(HERE, "data")
OUT = os.path.join(ROOT, "src", "tables")

INDEXES_URL = "https://encoding.spec.whatwg.org/indexes.json"
ENCODINGS_URL = "https://encoding.spec.whatwg.org/encodings.json"

HEADER = """\
// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.
"""


def fetch(url, name):
    """Reads the checked-in copy of an upstream resource, downloading it if absent.

    The copies live in tools/data/ so that regenerating is deterministic and works
    offline.  Delete one and re-run to pick up upstream changes."""
    os.makedirs(DATA, exist_ok=True)
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        if "--offline" in sys.argv:
            sys.exit("missing {} and --offline was given".format(path))
        with urllib.request.urlopen(url) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, "rb") as f:
        return json.loads(f.read())


def rows(values, per_line, fmt):
    out = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        out.append("    " + " ".join(fmt(v) + "," for v in chunk))
    return "\n".join(out)


def u16_hex(v):
    return "0x{:04X}".format(v)


def u32_hex(v):
    return "0x{:04X}".format(v)


def decode_table(name, index, width):
    """A pointer-indexed decode table.  0 means "no code point at this pointer"."""
    values = [0 if v is None else v for v in index]
    assert all(v <= 0xFFFF for v in values) or width == 32
    ty = "u16" if width == 16 else "u32"
    per = 16 if width == 16 else 12
    body = rows(values, per, u16_hex if width == 16 else u32_hex)
    return "#[rustfmt::skip]\npub static {}: [{}; {}] = [\n{}\n];\n".format(
        name, ty, len(values), body)


def encode_table(name, pairs, cp_width, gate=None):
    """Parallel arrays sorted by code point, plus a bucket index over the high byte.

    The encoders binary search these, and searching all of a 24000-entry table
    costs fifteen unpredictable branches over data that does not fit in cache.
    `BUCKETS[h]` is where code points whose high byte is `h` begin, so a lookup
    searches only its own bucket: a few probes over a contiguous run.  Code
    points above the basic multilingual plane share the final bucket.

    `gate` repeats the caller's `#[cfg(...)]` on the later arrays, since an
    attribute written above the call only covers the first."""
    cps = [cp for cp, _ in pairs]
    ptrs = [p for _, p in pairs]
    assert cps == sorted(cps)
    assert all(p <= 0xFFFF for p in ptrs)
    assert len(cps) < 0x10000, "bucket offsets are u16"
    # buckets[h] is the first index whose code point has a high byte >= h; the
    # 257th entry closes the last bucket.
    buckets = []
    at = 0
    for high in range(257):
        while at < len(cps) and min(cps[at] >> 8, 0x100) < high:
            at += 1
        buckets.append(at)
    buckets.append(len(cps))
    cp_ty = "u16" if cp_width == 16 else "u32"
    also = "#[cfg({})]\n".format(gate) if gate else ""
    out = "#[rustfmt::skip]\npub static {}_CODE_POINTS: [{}; {}] = [\n{}\n];\n\n".format(
        name, cp_ty, len(cps), rows(cps, 16 if cp_width == 16 else 12, u32_hex))
    out += "{}#[rustfmt::skip]\npub static {}_POINTERS: [u16; {}] = [\n{}\n];\n\n".format(
        also, name, len(ptrs), rows(ptrs, 16, u16_hex))
    out += "{}#[rustfmt::skip]\npub static {}_BUCKETS: [u16; {}] = [\n{}\n];\n".format(
        also, name, len(buckets), rows(buckets, 16, u16_hex))
    return out


def first_pointers(index, skip=None):
    """`index pointer for code point`: the first pointer for each code point."""
    seen = {}
    for pointer, cp in enumerate(index):
        if cp is None:
            continue
        if skip is not None and skip(pointer):
            continue
        if cp not in seen:
            seen[cp] = pointer
    return sorted(seen.items())


def big5_pointers(index):
    """`index Big5 pointer`: skips the HKSCS extensions, and prefers the *last*
    pointer for six code points that would otherwise round-trip to an extension."""
    last = {0x2550, 0x255E, 0x2561, 0x256A, 0x5341, 0x5345}
    lowest = (0xA1 - 0x81) * 157
    seen = {}
    for pointer, cp in enumerate(index):
        if cp is None or pointer < lowest:
            continue
        if cp in last or cp not in seen:
            seen[cp] = pointer
    return sorted(seen.items())


# Names as they appear in indexes.json, mapped to the Rust identifier we expose.
SINGLE_BYTE = [
    ("ibm866", "IBM866"),
    ("iso-8859-2", "ISO_8859_2"),
    ("iso-8859-3", "ISO_8859_3"),
    ("iso-8859-4", "ISO_8859_4"),
    ("iso-8859-5", "ISO_8859_5"),
    ("iso-8859-6", "ISO_8859_6"),
    ("iso-8859-7", "ISO_8859_7"),
    ("iso-8859-8", "ISO_8859_8"),
    ("iso-8859-10", "ISO_8859_10"),
    ("iso-8859-13", "ISO_8859_13"),
    ("iso-8859-14", "ISO_8859_14"),
    ("iso-8859-15", "ISO_8859_15"),
    ("iso-8859-16", "ISO_8859_16"),
    ("koi8-r", "KOI8_R"),
    ("koi8-u", "KOI8_U"),
    ("macintosh", "MACINTOSH"),
    ("windows-874", "WINDOWS_874"),
    ("windows-1250", "WINDOWS_1250"),
    ("windows-1251", "WINDOWS_1251"),
    ("windows-1252", "WINDOWS_1252"),
    ("windows-1253", "WINDOWS_1253"),
    ("windows-1254", "WINDOWS_1254"),
    ("windows-1255", "WINDOWS_1255"),
    ("windows-1256", "WINDOWS_1256"),
    ("windows-1257", "WINDOWS_1257"),
    ("windows-1258", "WINDOWS_1258"),
    ("x-mac-cyrillic", "X_MAC_CYRILLIC"),
]

# WHATWG encoding name -> the `VariantEncoding` arm implementing it.  The
# single-byte encodings are absent; they all share `VariantEncoding::SingleByte`.
VARIANTS = {
    "UTF-8": "Utf8",
    "GBK": "Gb18030 { is_gbk: true }",
    "gb18030": "Gb18030 { is_gbk: false }",
    "Big5": "Big5",
    "EUC-JP": "EucJp",
    "ISO-2022-JP": "Iso2022Jp",
    "Shift_JIS": "ShiftJis",
    "EUC-KR": "EucKr",
    "replacement": "Replacement",
    "UTF-16BE": "Utf16Be",
    "UTF-16LE": "Utf16Le",
    "x-user-defined": "XUserDefined",
}

# The one-line doc on each public static; anything absent gets its own name.
ENCODING_DOCS = {
    "UTF-8": "UTF-8, the encoding every new format should use.",
    "ISO-8859-8-I": "ISO-8859-8-I, identical to [`ISO_8859_8`] except in its name and implied text direction.",
    "GBK": "GBK, which decodes as [`GB18030`] but whose encoder emits only two-byte sequences.",
    "gb18030": "gb18030, the Chinese national standard, which covers all of Unicode.",
    "replacement": "The `replacement` encoding, which decodes any non-empty input to a single U+FFFD.",
    "UTF-16BE": "UTF-16BE.  Decode only; encoding to it yields UTF-8, per `get an output encoding`.",
    "UTF-16LE": "UTF-16LE.  Decode only; encoding to it yields UTF-8, per `get an output encoding`.",
    "x-user-defined": "x-user-defined, which maps bytes 0x80 to 0xFF into the private use area.",
    "Big5": "Big5, with the Hong Kong Supplementary Character Set extensions.",
    "EUC-JP": "EUC-JP.  Its decoder also accepts JIS X 0212 via the 0x8F prefix.",
    "ISO-2022-JP": "ISO-2022-JP, the only stateful encoding in the standard.",
    "Shift_JIS": "Shift_JIS, including the Windows end-user defined character range.",
    "EUC-KR": "EUC-KR, in practice the Unified Hangul Code (Windows codepage 949).",
}

# WHATWG encoding name -> the Cargo feature its tables live behind.  `None` means
# the encoding needs no tables and is always present.
FEATURES = {
    "UTF-8": None,
    "UTF-16BE": None,
    "UTF-16LE": None,
    "replacement": None,
    "x-user-defined": None,
    "GBK": "gb18030",
    "gb18030": "gb18030",
    "Big5": "big5",
    "EUC-JP": "euc-jp",
    "ISO-2022-JP": "iso-2022-jp",
    "Shift_JIS": "shift-jis",
    "EUC-KR": "euc-kr",
    # Everything else is one of the 28 legacy single-byte encodings.
}


def feature(name):
    return FEATURES.get(name, "single-byte")


def cfg(name):
    """The `#[cfg(...)]` line gating `name`, or an empty string if always on."""
    f = feature(name)
    return "" if f is None else '#[cfg(feature = "{}")]\n'.format(f)


# WHATWG encoding name -> the Rust `Encoding` constant in `crate::encodings`.
CONST_NAMES = {
    "UTF-8": "UTF_8_INIT",
    "IBM866": "IBM866_INIT",
    "ISO-8859-2": "ISO_8859_2_INIT",
    "ISO-8859-3": "ISO_8859_3_INIT",
    "ISO-8859-4": "ISO_8859_4_INIT",
    "ISO-8859-5": "ISO_8859_5_INIT",
    "ISO-8859-6": "ISO_8859_6_INIT",
    "ISO-8859-7": "ISO_8859_7_INIT",
    "ISO-8859-8": "ISO_8859_8_INIT",
    "ISO-8859-8-I": "ISO_8859_8_I_INIT",
    "ISO-8859-10": "ISO_8859_10_INIT",
    "ISO-8859-13": "ISO_8859_13_INIT",
    "ISO-8859-14": "ISO_8859_14_INIT",
    "ISO-8859-15": "ISO_8859_15_INIT",
    "ISO-8859-16": "ISO_8859_16_INIT",
    "KOI8-R": "KOI8_R_INIT",
    "KOI8-U": "KOI8_U_INIT",
    "macintosh": "MACINTOSH_INIT",
    "windows-874": "WINDOWS_874_INIT",
    "windows-1250": "WINDOWS_1250_INIT",
    "windows-1251": "WINDOWS_1251_INIT",
    "windows-1252": "WINDOWS_1252_INIT",
    "windows-1253": "WINDOWS_1253_INIT",
    "windows-1254": "WINDOWS_1254_INIT",
    "windows-1255": "WINDOWS_1255_INIT",
    "windows-1256": "WINDOWS_1256_INIT",
    "windows-1257": "WINDOWS_1257_INIT",
    "windows-1258": "WINDOWS_1258_INIT",
    "x-mac-cyrillic": "X_MAC_CYRILLIC_INIT",
    "GBK": "GBK_INIT",
    "gb18030": "GB18030_INIT",
    "Big5": "BIG5_INIT",
    "EUC-JP": "EUC_JP_INIT",
    "ISO-2022-JP": "ISO_2022_JP_INIT",
    "Shift_JIS": "SHIFT_JIS_INIT",
    "EUC-KR": "EUC_KR_INIT",
    "replacement": "REPLACEMENT_INIT",
    "UTF-16BE": "UTF_16BE_INIT",
    "UTF-16LE": "UTF_16LE_INIT",
    "x-user-defined": "X_USER_DEFINED_INIT",
}




# --- labels the standard reassigns ------------------------------------------
#
# Each of these names one charset and is resolved by the standard to a
# different one, almost always a superset that a browser is more likely to have
# meant.  `Encoding::for_label` must not do that: a caller asking for
# ISO-8859-1 and silently getting windows-1252 has had byte 0x80 turn into a
# euro sign behind its back.  They stay reachable through
# `Encoding::for_whatwg_label`, which is the whole point of that lookup being
# separate.
#
# Where the named charset exists in this crate the general table points at it
# instead; where it does not, the general lookup answers None.
#
# The test is whether the substitution *remaps*: whether some byte sequence
# valid in the named charset decodes to a different character.  Measured
# against the authoritative tables, windows-1252 remaps 27 of ISO-8859-1's
# bytes, windows-1254 25 of ISO-8859-9's, windows-874 9 of TIS-620's, WHATWG's
# Big5 260 of Big5's pointers, its jis0208 7 of JIS X 0208's, and GBK 2 of
# GB 2312's.  Those are lies and are listed here.
#
# The Korean labels are deliberately absent: WHATWG's EUC-KR is the Unified
# Hangul Code, which contains all 8224 of KS X 1001 with *zero* remapped,
# so a caller asking for `ks_c_5601-1987` and getting it back is given the
# same answer for every byte sequence its own charset defines.  A lenient
# superset is not a lie.
WHATWG_ONLY_LABELS = {
    # ISO-8859-1 and US-ASCII are not windows-1252; 0x80 is U+0080, not U+20AC.
    "ansi_x3.4-1968", "ascii", "us-ascii", "cp819", "csisolatin1", "ibm819",
    "iso-8859-1", "iso-ir-100", "iso8859-1", "iso88591", "iso_8859-1",
    "iso_8859-1:1987", "l1", "latin1",
    # ISO-8859-9 is not windows-1254.
    "csisolatin5", "iso-8859-9", "iso-ir-148", "iso8859-9", "iso88599",
    "iso_8859-9", "iso_8859-9:1989", "l5", "latin5",
    # TIS-620 and ISO-8859-11 are not windows-874, and neither is DOS-874.
    "dos-874", "iso-8859-11", "iso8859-11", "iso885911", "tis-620",
    # GB 2312 is a subset of GBK, not GBK.
    "chinese", "csgb2312", "csiso58gb231280", "gb2312", "gb_2312",
    "gb_2312-80", "iso-ir-58",
    # Real encodings the standard neutralizes.  A caller that wants one should
    # be told this build has no such thing, not handed `replacement`.
    "csiso2022kr", "hz-gb-2312", "iso-2022-cn", "iso-2022-cn-ext",
    "iso-2022-kr",
}

# --- charsets outside the Encoding Standard ---------------------------------
#
# Mapping data comes from the Unicode Consortium's MAPPINGS archive, whose files
# are checked in under tools/data/mappings/.  `full` marks a charset whose bytes
# below 0x80 are not plain ASCII, which needs a 256-entry table rather than the
# 128-entry one the standard's single-byte encodings use.
#
# (group, name, ident, mapping file, Windows code page or None, labels, full)
EXTRA = [
    # The ISO 8859 parts the standard resolves to a Windows superset instead.
    # ISO-8859-2 through -8, -10 and -13 through -16 are byte-for-byte what the
    # standard already carries, so only these two are missing; ISO-8859-1 needs
    # no table at all and lives with the algorithmic charsets below.
    ("single-byte", "ISO-8859-9", "ISO_8859_9", "8859-9.TXT", 28599,
     ["iso-8859-9", "iso8859-9", "iso88599", "iso_8859-9", "iso_8859-9:1989",
      "iso-ir-148", "latin5", "l5", "csisolatin5"], False),
    ("single-byte", "ISO-8859-11", "ISO_8859_11", "8859-11.TXT", None,
     ["iso-8859-11", "iso8859-11", "iso885911", "iso_8859-11", "tis-620",
      "iso-ir-166", "cstis620"], False),

    # IBM PC / OEM code pages.  437 and 874 are omitted: the standard already
    # has IBM866 and windows-874, and CP866 is byte-for-byte identical.
    ("dos", "IBM437", "IBM437", "CP437.TXT", 437,
     ["cp437", "ibm437", "cspc8codepage437", "oem-us"], False),
    ("dos", "IBM737", "IBM737", "CP737.TXT", 737, ["cp737", "ibm737"], False),
    ("dos", "IBM775", "IBM775", "CP775.TXT", 775,
     ["cp775", "ibm775", "cspc775baltic"], False),
    ("dos", "IBM850", "IBM850", "CP850.TXT", 850,
     ["cp850", "ibm850", "cspc850multilingual"], False),
    ("dos", "IBM852", "IBM852", "CP852.TXT", 852, ["cp852", "ibm852", "cspcp852"], False),
    ("dos", "IBM855", "IBM855", "CP855.TXT", 855, ["cp855", "ibm855", "csibm855"], False),
    ("dos", "IBM856", "IBM856", "CP856.TXT", None, ["cp856", "ibm856"], False),
    ("dos", "IBM857", "IBM857", "CP857.TXT", 857, ["cp857", "ibm857", "csibm857"], False),
    ("dos", "IBM860", "IBM860", "CP860.TXT", 860, ["cp860", "ibm860", "csibm860"], False),
    ("dos", "IBM861", "IBM861", "CP861.TXT", 861,
     ["cp861", "ibm861", "cp-is", "csibm861"], False),
    ("dos", "IBM862", "IBM862", "CP862.TXT", 862,
     ["cp862", "ibm862", "dos-862", "cspc862latinhebrew"], False),
    ("dos", "IBM863", "IBM863", "CP863.TXT", 863, ["cp863", "ibm863", "csibm863"], False),
    ("dos", "IBM864", "IBM864", "CP864.TXT", 864, ["cp864", "ibm864", "csibm864"], True),
    ("dos", "IBM865", "IBM865", "CP865.TXT", 865, ["cp865", "ibm865", "csibm865"], False),
    ("dos", "IBM869", "IBM869", "CP869.TXT", 869,
     ["cp869", "ibm869", "cp-gr", "csibm869"], False),
    ("dos", "IBM1006", "IBM1006", "CP1006.TXT", None, ["cp1006", "ibm1006"], False),

    # Apple's regional variants.  Mac OS Roman and Mac OS Cyrillic are the
    # standard's `macintosh` and `x-mac-cyrillic`; Hebrew and Thai are omitted
    # because Apple maps some of their bytes to two code points.
    ("mac", "x-mac-arabic", "X_MAC_ARABIC", "ARABIC.TXT", 10004,
     ["x-mac-arabic", "mac-arabic"], False),
    ("mac", "x-mac-celtic", "X_MAC_CELTIC", "CELTIC.TXT", None,
     ["x-mac-celtic", "mac-celtic"], False),
    ("mac", "x-mac-centraleurroman", "X_MAC_CENTRALEURROMAN", "CENTEURO.TXT", 10029,
     ["x-mac-centraleurroman", "mac-centraleurroman", "x-mac-ce"], False),
    ("mac", "x-mac-croatian", "X_MAC_CROATIAN", "CROATIAN.TXT", 10082,
     ["x-mac-croatian", "mac-croatian"], False),
    ("mac", "x-mac-farsi", "X_MAC_FARSI", "FARSI.TXT", None,
     ["x-mac-farsi", "mac-farsi"], False),
    ("mac", "x-mac-gaelic", "X_MAC_GAELIC", "GAELIC.TXT", None,
     ["x-mac-gaelic", "mac-gaelic"], False),
    ("mac", "x-mac-greek", "X_MAC_GREEK", "GREEK.TXT", 10006,
     ["x-mac-greek", "mac-greek"], False),
    ("mac", "x-mac-icelandic", "X_MAC_ICELANDIC", "ICELAND.TXT", 10079,
     ["x-mac-icelandic", "mac-icelandic"], False),
    ("mac", "x-mac-romanian", "X_MAC_ROMANIAN", "ROMANIAN.TXT", 10010,
     ["x-mac-romanian", "mac-romanian"], False),
    ("mac", "x-mac-turkish", "X_MAC_TURKISH", "TURKISH.TXT", 10081,
     ["x-mac-turkish", "mac-turkish"], False),

    # IBM mainframe EBCDIC.  These permute the whole byte range.
    ("ebcdic", "IBM037", "IBM037", "CP037.TXT", 37,
     ["cp037", "ibm037", "ebcdic-cp-us", "ebcdic-cp-ca", "ebcdic-cp-wt",
      "ebcdic-cp-nl", "csibm037"], True),
    ("ebcdic", "IBM424", "IBM424", "CP424.TXT", 20424,
     ["cp424", "ibm424", "ebcdic-cp-he", "csibm424"], True),
    ("ebcdic", "IBM500", "IBM500", "CP500.TXT", 500,
     ["cp500", "ibm500", "ebcdic-cp-be", "ebcdic-cp-ch", "csibm500"], True),
    ("ebcdic", "IBM875", "IBM875", "CP875.TXT", 875, ["cp875", "ibm875"], True),
    ("ebcdic", "IBM1026", "IBM1026", "CP1026.TXT", 1026,
     ["cp1026", "ibm1026", "csibm1026"], True),

    # Everything else.
    ("misc", "Atari-ST", "ATARI_ST", "ATARIST.TXT", None, ["atari-st", "atarist"], False),
    ("misc", "KZ-1048", "KZ_1048", "KZ1048.TXT", None,
     ["kz-1048", "kz1048", "strk1048-2002", "rk1048", "cskz1048"], False),
]

# Charsets outside the standard that need no table.
# (group, name, ident, variant, Windows code page or None, labels)
ALGORITHMIC = [
    # Always present: no table, and the standard resolves their labels to
    # windows-1252 instead, so a caller that wants the real thing has nowhere
    # else to go.
    (None, "ISO-8859-1", "ISO_8859_1", "Identity(crate::identity::Identity::latin1())", 28591,
     ["iso-8859-1", "iso8859-1", "iso88591", "iso_8859-1", "iso_8859-1:1987",
      "iso-ir-100", "latin1", "l1", "cp819", "ibm819", "csisolatin1"]),
    (None, "US-ASCII", "US_ASCII", "Identity(crate::identity::Identity::ascii())", 20127,
     ["us-ascii", "ascii", "ansi_x3.4-1968", "iso-ir-6", "iso646-us", "us", "csascii",
      "iso_646.irv:1991", "ansi_x3.4-1986"]),
    # GB 2312-80, which reuses index gb18030 and so rides its feature.
    ("gb18030", "GB2312", "GB2312", "Gb2312", 20936,
     ["gb2312", "gb_2312", "gb_2312-80", "gb2312-80", "chinese", "csgb2312",
      "csiso58gb231280", "iso-ir-58", "euc-cn", "x-euc-cn"]),
    ("unicode-extras", "UTF-32BE", "UTF_32BE", "Utf32Be", 12001,
     ["utf-32be", "utf32be"]),
    ("unicode-extras", "UTF-32LE", "UTF_32LE", "Utf32Le", 12000,
     ["utf-32", "utf-32le", "utf32", "utf32le"]),
    ("unicode-extras", "UTF-7", "UTF_7", "Utf7", 65000,
     ["utf-7", "utf7", "unicode-1-1-utf-7", "csunicode11utf7"]),
]

MAPPINGS = os.path.join(HERE, "data", "mappings")


def load_mapping(filename):
    """Parses a Unicode MAPPINGS file into a 256-entry byte -> code point table."""
    table = [None] * 256
    with open(os.path.join(MAPPINGS, filename), encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            if not parts[0].lower().startswith("0x") or not parts[1].lower().startswith("0x"):
                continue
            assert "+" not in parts[1], "{}: multi-code-point mapping".format(filename)
            byte = int(parts[0], 16)
            if byte < 256:
                table[byte] = int(parts[1], 16)
    return table




UNASSIGNED = 0xFFFF


def emit_gb2312(indexes):
    """GB 2312-80, as a narrowing of the standard's index gb18030.

    GB 2312 is EUC-CN's G1 set: lead 0xA1-0xF7, trail 0xA1-0xFE.  Every one of
    its 7445 code points is in index gb18030, and the two disagree at exactly
    two pointers, so the charset needs no table of its own — only the byte
    range and those two overrides.

    Source: glibc-EUC_CN-2.3.3.ucm from unicode-org/icu-data, which reproduces
    Unicode's withdrawn MAPPINGS/OBSOLETE/EASTASIA/GB/GB2312.TXT (Unicode 3.0,
    table version 1.0, 1999-10-08) bit for bit over the two-byte range.
    """
    entries = {}
    path = os.path.join(MAPPINGS, "GB2312-EUC_CN.ucm")
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            m = re.match(r"<U([0-9A-Fa-f]{4,6})>\s+((?:\\x[0-9A-Fa-f]{2})+)\s+\|0", line)
            if not m:
                continue
            code_point = int(m.group(1), 16)
            byte_seq = [int(b, 16) for b in re.findall(r"\\x([0-9A-Fa-f]{2})", m.group(2))]
            if len(byte_seq) == 2:
                entries[(byte_seq[0], byte_seq[1])] = code_point
    assert len(entries) == 7445, len(entries)
    leads = {lead for lead, _ in entries}
    trails = {trail for _, trail in entries}
    assert (min(leads), max(leads)) == (0xA1, 0xF7), (min(leads), max(leads))
    assert (min(trails), max(trails)) == (0xA1, 0xFE), (min(trails), max(trails))
    # Level 1 and level 2 hanzi, as GB 2312-80 defines them.
    level1 = sum(1 for (lead, _), _ in entries.items() if 0xB0 <= lead <= 0xD7)
    level2 = sum(1 for (lead, _), _ in entries.items() if 0xD8 <= lead <= 0xF7)
    assert (level1, level2) == (3755, 3008), (level1, level2)

    # The byte range alone is not the charset: GBK fills rows 10 to 15, which
    # GB 2312 leaves unassigned, and those rows sit inside the lead range.  So
    # the delta carries both the corrections and the exclusions.
    gb = indexes["gb18030"]
    decode_delta, encode_delta = [], []
    remaps = 0
    for lead in range(0xA1, 0xF8):
        for trail in range(0xA1, 0xFF):
            pointer = (lead - 0x81) * 190 + (trail - 0x41)
            mine = entries.get((lead, trail))
            theirs = gb[pointer]
            if mine == theirs:
                continue
            if mine is None:
                decode_delta.append((pointer, UNASSIGNED))
            else:
                remaps += 1
                decode_delta.append((pointer, mine))
                encode_delta.append((mine, pointer))
    assert remaps == 2, remaps
    assert len(decode_delta) == 735, len(decode_delta)
    decode_delta.sort()
    encode_delta.sort()
    parts = [HEADER, """
//! GB 2312-80, expressed as a narrowing of index gb18030.
//!
//! Lead 0xA1 to 0xF7, trail 0xA1 to 0xFE, minus the 733 pointers GBK fills in
//! rows 10 to 15 that GB 2312 leaves unassigned, and corrected at the two
//! pointers where GBK gives a different character.  The remaining 7443 code
//! points index gb18030 already holds unchanged, so there is no table here.

/// Where GB 2312-80 differs from index gb18030 inside its own byte range:
/// `0xFFFF` for a pointer GB 2312 leaves unassigned and GBK fills, and the code
/// point itself for the two GBK gets wrong.
#[rustfmt::skip]
pub static GB2312_DECODE_DELTA: [(u16, u16); %d] = [
%s
];

/// The same overrides by code point, for the encoder.
#[rustfmt::skip]
pub static GB2312_ENCODE_DELTA: [(u16, u16); %d] = [
%s
];
""" % (
        len(decode_delta),
        "\n".join("    (0x{:04X}, 0x{:04X}),".format(a, b) for a, b in decode_delta),
        len(encode_delta),
        "\n".join("    (0x{:04X}, 0x{:04X}),".format(a, b) for a, b in encode_delta),
    )]
    write(os.path.join(OUT, "gb2312.rs"), "".join(parts))
    return decode_delta


def emit_extra(indexes):
    """Writes the tables, `Encoding`s, labels and code pages for EXTRA."""
    groups = sorted({g for g, *_ in EXTRA})
    parts = [HEADER, """
//! Tables for the charsets outside the WHATWG Encoding Standard.
//!
//! Generated from the Unicode Consortium's MAPPINGS archive.  A `_DECODE` table
//! holding 128 entries covers bytes 0x80 to 0xFF, with 0 for an unmapped byte;
//! one holding 256 entries covers every byte, with 0xFFFF for an unmapped one,
//! because those charsets map a byte to U+0000.

"""]
    used_labels = set()
    code_pages = []
    for group, name, ident, filename, cp, labels, full in EXTRA:
        table = load_mapping(filename)
        gate = '#[cfg(feature = "{}")]\n'.format(group)
        if full:
            values = [0xFFFF if v is None else v for v in table]
            assert all(v <= 0xFFFF for v in values), name
            assert 0xFFFF not in [v for v in table if v is not None], name
            parts.append("\n/// {} ({})\n".format(name, filename))
            parts.append(gate)
            parts.append("#[rustfmt::skip]\npub static {}_DECODE: [u16; 256] = [\n{}\n];\n".format(
                ident, rows(values, 12, u16_hex)))
            pairs = sorted({v: b for b, v in reversed(list(enumerate(table))) if v is not None}.items())
        else:
            for b in range(0x80):
                assert table[b] in (None, b), "{}: byte {:#04x} is not ASCII".format(name, b)
            values = [0 if table[b] is None else table[b] for b in range(0x80, 0x100)]
            assert 0 not in [v for v in table[0x80:] if v is not None], name
            parts.append("\n/// {} ({})\n".format(name, filename))
            parts.append(gate)
            parts.append("#[rustfmt::skip]\npub static {}_DECODE: [u16; 128] = [\n{}\n];\n".format(
                ident, rows(values, 12, u16_hex)))
            pairs = sorted({v: b for b, v in reversed(list(enumerate(table)))
                            if v is not None and b >= 0x80}.items())
        cps = [cp_ for cp_, _ in pairs]
        bytes_ = [b for _, b in pairs]
        parts.append(gate)
        parts.append("#[rustfmt::skip]\npub static {}_ENCODE_CODE_POINTS: [u16; {}] = [\n{}\n];\n".format(
            ident, len(cps), rows(cps, 12, u16_hex)))
        parts.append(gate)
        parts.append("#[rustfmt::skip]\npub static {}_ENCODE_BYTES: [u8; {}] = [\n{}\n];\n".format(
            ident, len(bytes_), rows(bytes_, 16, lambda v: "0x{:02X}".format(v))))
        for label in labels:
            assert label not in used_labels, "duplicate label " + label
            used_labels.add(label)
        if cp is not None:
            code_pages.append((cp, ident, group))
    for group, _n, ident, _v, cp, labels in ALGORITHMIC:
        for label in labels:
            assert label not in used_labels, "duplicate label " + label
            used_labels.add(label)
        if cp is not None:
            code_pages.append((cp, ident, group))
    write(os.path.join(OUT, "extra.rs"), "".join(parts))

    # The Encoding constants and statics.
    parts = [HEADER, """
//! The [`Encoding`] instances for the charsets outside the standard.

use crate::Encoding;
// A build may take only the charsets that need no table.
#[cfg(any(\n    feature = "dos",\n    feature = "ebcdic",\n    feature = "mac",\n    feature = "misc",\n    feature = "single-byte"\n))]
#[allow(unused_imports)]
use crate::tables::extra as t;
use crate::variant::VariantEncoding;
"""]
    for group in groups:
        parts.append("\n// {}\n".format(GROUP_DOCS[group]))
        for g, name, ident, _f, _cp, _labels, full in EXTRA:
            if g != group:
                continue
            arm = "FullByte" if full else "SingleByte"
            parts.append(
                '\n#[cfg(feature = "{g}")]\npub(crate) const {i}_INIT: Encoding = Encoding::new(\n'
                '    "{n}",\n    VariantEncoding::{arm}(\n        &t::{i}_DECODE,\n'
                '        &t::{i}_ENCODE_CODE_POINTS,\n        &t::{i}_ENCODE_BYTES,\n    ),\n);\n'
                .format(g=g, i=ident, n=name, arm=arm))
            parts.append('/// {n}\n#[cfg(feature = "{g}")]\npub static {i}: &Encoding = &{i}_INIT;\n'
                         .format(g=g, i=ident, n=name))
    parts.append("\n// Algorithmic charsets, which need no table\n")
    for group, name, ident, variant, _cp, _labels in ALGORITHMIC:
        gate = "" if group is None else '#[cfg(feature = "{}")]\n'.format(group)
        parts.append(
            '\n{g}pub(crate) const {i}_INIT: Encoding =\n'
            '    Encoding::new("{n}", VariantEncoding::{v});\n'.format(g=gate, i=ident, n=name, v=variant))
        parts.append('/// {n}\n{g}pub static {i}: &Encoding = &{i}_INIT;\n'
                     .format(g=gate, i=ident, n=name))
    write(os.path.join(ROOT, "src", "extra_encodings.rs"), "".join(parts))

    # Labels and code pages, merged into the tables the lookups read.
    label_rows = sorted(
        [(l, ident, group) for group, _n, ident, _f, _cp, labels, _full in EXTRA for l in labels]
        + [(l, ident, group) for group, _n, ident, _v, _cp, labels in ALGORITHMIC for l in labels])
    for label, _i, _g in label_rows:
        assert label not in used_labels or True
    parts = [HEADER, """
//! Windows code pages for the charsets outside the standard.

use crate::code_page::CodePage;
// A group may have no Windows code pages of its own.
#[allow(unused_imports)]
use crate::extra_encodings as x;
"""]
    parts.append("")
    parts.append("\n/// Sorted by number, for binary search.\n")
    parts.append("pub static EXTRA_CODE_PAGES: &[CodePage] = &[\n")
    for cp, ident, group in sorted(code_pages):
        gate = "" if group is None else '    #[cfg(feature = "{}")]\n'.format(group)
        parts.append('{}    CodePage {{ number: {}, encoding: &x::{}_INIT, canonical: true }},\n'
                     .format(gate, cp, ident))
    parts.append("];\n")
    write(os.path.join(OUT, "extra_labels.rs"), "".join(parts))
    return label_rows


GROUP_DOCS = {
    "single-byte": "ISO 8859 parts the standard resolves elsewhere",
    "dos": "IBM PC / OEM code pages",
    "mac": "Apple's regional variants of Mac OS Roman",
    "ebcdic": "IBM mainframe EBCDIC code pages",
    "misc": "Everything else",
}



# --- transliteration --------------------------------------------------------
#
# Unicode's own decompositions do most of the work: recursively expand a
# character, drop the combining marks, and if what remains is ASCII that is the
# fold.  The table below covers what does not decompose at all — ligatures,
# stroked letters, punctuation and symbols — and the non-ASCII characters that
# appear inside a decomposition, such as U+2044 FRACTION SLASH in `½`.
TRANSLIT_EXTRA = {
    # Letters with no decomposition.
    0x00C6: "AE", 0x00E6: "ae", 0x0152: "OE", 0x0153: "oe",
    0x00DF: "ss", 0x1E9E: "SS", 0x00D8: "O", 0x00F8: "o",
    0x0110: "D", 0x0111: "d", 0x0141: "L", 0x0142: "l",
    0x00DE: "TH", 0x00FE: "th", 0x00D0: "D", 0x00F0: "d",
    0x014A: "NG", 0x014B: "ng", 0x0138: "k", 0x017F: "s",
    0x0131: "i", 0x0132: "IJ", 0x0133: "ij", 0x0126: "H", 0x0127: "h",
    0x0166: "T", 0x0167: "t", 0x018F: "E", 0x0259: "e",
    0x0180: "b", 0x0183: "b", 0x0288: "t", 0x01BF: "w", 0x01BD: "z",
    # Punctuation.
    0x2010: "-", 0x2011: "-", 0x2012: "-", 0x2013: "-", 0x2014: "-", 0x2015: "-",
    0x2018: "'", 0x2019: "'", 0x201A: "'", 0x201B: "'",
    0x201C: '"', 0x201D: '"', 0x201E: '"', 0x201F: '"',
    0x2032: "'", 0x2033: '"', 0x2035: "'", 0x2036: '"',
    0x00AB: "<<", 0x00BB: ">>", 0x2039: "<", 0x203A: ">",
    0x2026: "...", 0x2022: "*", 0x2023: ">", 0x00B7: ".", 0x2027: ".",
    0x203E: "-", 0x2044: "/", 0x2215: "/", 0x2212: "-",
    0x00A1: "!", 0x00BF: "?", 0x00AD: "-",
    # Symbols.
    0x00A9: "(C)", 0x00AE: "(R)", 0x2122: "(TM)", 0x2117: "(P)",
    0x00B0: "deg", 0x00B1: "+/-", 0x00D7: "x", 0x00F7: "/",
    0x00AC: "!", 0x00A6: "|", 0x00A7: "S", 0x00B6: "P",
    0x2020: "+", 0x2021: "++", 0x2030: "%o", 0x2031: "%oo", 0x2116: "No",
    0x2190: "<-", 0x2192: "->", 0x2194: "<->", 0x21D2: "=>", 0x21D4: "<=>",
    0x2264: "<=", 0x2265: ">=", 0x2260: "!=", 0x2248: "~", 0x221E: "inf",
    0x221A: "sqrt", 0x2211: "sum", 0x220F: "prod", 0x222B: "int", 0x2202: "d",
    0x25CF: "*", 0x25CB: "o", 0x25A0: "#", 0x25A1: "#",
    # Currency.
    0x20AC: "EUR", 0x00A3: "GBP", 0x00A5: "JPY", 0x00A2: "c", 0x00A4: "$",
    0x20A9: "KRW", 0x20B9: "INR", 0x20BD: "RUB", 0x20B4: "UAH", 0x20AB: "VND",
}


def build_translit():
    """Code point -> ASCII replacement, for every BMP character that has one."""
    decomposition = {}
    category = {}
    with open(os.path.join(DATA, "UnicodeData.txt"), encoding="utf-8") as f:
        for line in f:
            fields = line.split(";")
            code_point = int(fields[0], 16)
            category[code_point] = fields[2]
            if fields[5]:
                decomposition[code_point] = fields[5]

    def expand(code_point, depth=0):
        if depth > 8 or code_point not in decomposition:
            return [code_point]
        parts = decomposition[code_point].split()
        if parts and parts[0].startswith("<"):
            parts = parts[1:]
        out = []
        for part in parts:
            out.extend(expand(int(part, 16), depth + 1))
        return out

    folds = {}
    for code_point in range(0x20, 0x10000):
        if code_point <= 0x7E:
            continue
        text = TRANSLIT_EXTRA.get(code_point)
        if text is None:
            expanded = [c for c in expand(code_point) if category.get(c) != "Mn"]
            # Substitute any non-ASCII piece from the table above, once.
            pieces = []
            for c in expanded:
                pieces.append(chr(c) if c <= 0x7E else TRANSLIT_EXTRA.get(c, "\uFFFF"))
            text = "".join(pieces)
        if not text or any(ch < " " or ch > "~" for ch in text):
            continue
        if text == chr(code_point):
            continue
        folds[code_point] = text
    return dict(sorted(folds.items()))


def write(path, text):
    with open(path, "w", newline="\n") as f:
        f.write(text)
    print("wrote {} ({} bytes)".format(os.path.relpath(path, ROOT), len(text)))


def main():
    indexes = fetch(INDEXES_URL, "indexes.json")
    encodings = fetch(ENCODINGS_URL, "encodings.json")
    os.makedirs(OUT, exist_ok=True)

    # --- single-byte -----------------------------------------------------
    parts = [HEADER, "\n//! Decode and encode tables for the legacy single-byte encodings.\n"]
    for json_name, rust_name in SINGLE_BYTE:
        index = indexes[json_name]
        assert len(index) == 128
        parts.append("\n/// index {}\n".format(json_name))
        parts.append(decode_table(rust_name + "_DECODE", index, 16))
        pairs = first_pointers(index)
        cps = [cp for cp, _ in pairs]
        ptrs = [p for _, p in pairs]
        parts.append("\n#[rustfmt::skip]\npub static {}_ENCODE_CODE_POINTS: [u16; {}] = [\n{}\n];\n".format(
            rust_name, len(cps), rows(cps, 16, u16_hex)))
        parts.append("\n#[rustfmt::skip]\npub static {}_ENCODE_BYTES: [u8; {}] = [\n{}\n];\n".format(
            rust_name, len(ptrs), rows([p + 0x80 for p in ptrs], 16, lambda v: "0x{:02X}".format(v))))
    write(os.path.join(OUT, "single_byte.rs"), "".join(parts))

    # --- big5 ------------------------------------------------------------
    big5 = indexes["big5"]
    parts = [HEADER, "\n//! index Big5.\n\n"]
    parts.append(decode_table("BIG5_DECODE", big5, 32))
    parts.append("\n")
    parts.append(encode_table("BIG5_ENCODE", big5_pointers(big5), 32))
    write(os.path.join(OUT, "big5.rs"), "".join(parts))

    # --- gb18030 ---------------------------------------------------------
    gb = indexes["gb18030"]
    parts = [HEADER, "\n//! index gb18030 and index gb18030 ranges.\n\n"]
    parts.append(decode_table("GB18030_DECODE", gb, 16))
    parts.append("\n")
    parts.append(encode_table("GB18030_ENCODE", first_pointers(gb), 16))
    ranges = indexes["gb18030-ranges"]
    parts.append("\n/// index gb18030 ranges: (pointer, code point) pairs, sorted by both.\n")
    parts.append("#[rustfmt::skip]\npub static GB18030_RANGES: [(u32, u32); {}] = [\n{}\n];\n".format(
        len(ranges),
        "\n".join("    (0x{:05X}, 0x{:05X}),".format(p, c) for p, c in ranges)))
    write(os.path.join(OUT, "gb18030.rs"), "".join(parts))

    # --- jis0208 / jis0212 / iso-2022-jp katakana ------------------------
    jis0208 = indexes["jis0208"]
    jis0212 = indexes["jis0212"]
    katakana = indexes["iso-2022-jp-katakana"]
    # Three encodings share index jis0208, so each static is gated on exactly
    # the features that read it.
    jp = 'feature = "iso-2022-jp"'
    ej = 'feature = "euc-jp"'
    sj = 'feature = "shift-jis"'
    parts = [HEADER, "\n//! index jis0208, index jis0212 and index ISO-2022-JP katakana.\n\n"]
    parts.append(decode_table("JIS0208_DECODE", jis0208, 16))
    parts.append("\n/// Read only by EUC-JP, through the 0x8F prefix.\n")
    parts.append("#[cfg({})]\n".format(ej))
    parts.append(decode_table("JIS0212_DECODE", jis0212, 16))
    parts.append("\n/// `index pointer for code point in index jis0208`, used by EUC-JP and ISO-2022-JP.\n")
    parts.append("#[cfg(any({}, {}))]\n".format(ej, jp))
    parts.append(encode_table("JIS0208_ENCODE", first_pointers(jis0208), 16, gate="any({}, {})".format(ej, jp)))
    parts.append("\n/// `index Shift_JIS pointer`: index jis0208 without pointers 8272..=8835.\n")
    parts.append("#[cfg({})]\n".format(sj))
    parts.append(encode_table(
        "SHIFT_JIS_ENCODE",
        first_pointers(jis0208, skip=lambda p: 8272 <= p <= 8835),
        16,
        gate=sj))
    parts.append("\n/// index ISO-2022-JP katakana, indexed by `code point - 0xFF61`.\n")
    parts.append("#[cfg({})]\n".format(jp))
    parts.append("#[rustfmt::skip]\npub static ISO_2022_JP_KATAKANA: [u16; {}] = [\n{}\n];\n".format(
        len(katakana), rows(katakana, 16, u16_hex)))
    write(os.path.join(OUT, "jis.rs"), "".join(parts))

    # --- euc-kr ----------------------------------------------------------
    euckr = indexes["euc-kr"]
    parts = [HEADER, "\n//! index EUC-KR.\n\n"]
    parts.append(decode_table("EUC_KR_DECODE", euckr, 16))
    parts.append("\n")
    parts.append(encode_table("EUC_KR_ENCODE", first_pointers(euckr), 16))
    write(os.path.join(OUT, "euc_kr.rs"), "".join(parts))

    # --- labels ----------------------------------------------------------
    extra_rows = emit_extra(indexes)
    gb2312_delta = emit_gb2312(indexes)
    labels = []
    names = []
    for group in encodings:
        for enc in group["encodings"]:
            names.append(enc["name"])
            for label in enc["labels"]:
                labels.append((label, CONST_NAMES[enc["name"]]))
    by_const = {CONST_NAMES[n]: n for n in names}
    # The standard's own table keeps every label it defines, reassignments and
    # all.  The general table drops the reassigned ones and takes the charsets
    # from outside the standard instead — including ISO-8859-1 and US-ASCII,
    # which claim labels the standard hands to windows-1252.  The two tables
    # therefore disagree on 52 labels, by design; each must still be internally
    # unique, since each is binary searched.
    whatwg_labels = sorted(
        (label, const, feature(by_const[const]), "e") for label, const in labels)
    assert len(set(r[0] for r in whatwg_labels)) == len(whatwg_labels), "duplicate WHATWG label"
    all_labels = [r for r in whatwg_labels if r[0] not in WHATWG_ONLY_LABELS]
    all_labels += [(label, ident + "_INIT", group, "x") for label, ident, group in extra_rows]
    all_labels.sort(key=lambda r: r[0])
    duplicates = [r[0] for r in all_labels
                  if sum(1 for x in all_labels if x[0] == r[0]) > 1]
    assert not duplicates, "duplicate label in the general table: {}".format(sorted(set(duplicates)))
    parts = [HEADER, """
//! Every label the standard defines, sorted for binary search.
//!
//! An entry is present only when the encoding it names is compiled in, so the
//! table shrinks with the enabled table groups rather than pointing at
//! encodings that do not exist.

use crate::Encoding;
use crate::encodings as e;
use crate::extra_encodings as x;

/// Every label of every encoding compiled in, sorted for binary search.
///
/// Labels are already lowercase and trimmed; callers must normalize before
/// searching.  `whatwg` marks a label the Encoding Standard defines, which is
/// what lets the standard's own lookup refuse everything else.
pub struct Label {
    pub text: &'static str,
    pub encoding: &'static Encoding,
    pub whatwg: bool,
}

pub static LABELS: &[Label] = &[
"""]
    for label, const, group, module in all_labels:
        gate = "" if group is None else '    #[cfg(feature = "{}")]\n'.format(group)
        parts.append('{}    Label {{ text: "{}", encoding: &{}::{}, whatwg: {} }},\n'
                     .format(gate, label, module, const, "true" if module == "e" else "false"))
    parts.append("];\n\n")
    assert WHATWG_ONLY_LABELS <= {r[0] for r in whatwg_labels}, (
        "reassigned labels the standard does not define: {}".format(
            sorted(WHATWG_ONLY_LABELS - {r[0] for r in whatwg_labels})))

    # The standard's own table, which `for_whatwg_label` alone reads.
    parts.append("""/// Every label the WHATWG Encoding Standard defines, sorted for binary search.
///
/// This is the table `Encoding::for_whatwg_label` reads, and it is the only
/// place the standard's reassignments live: `iso-8859-1` to windows-1252,
/// `gb2312` to GBK, `iso-2022-kr` to replacement.  The general lookup must not
/// see them.
#[cfg(feature = "whatwg-aliases")]
pub static WHATWG_LABELS: &[Label] = &[
""")
    for label, const, group, _module in whatwg_labels:
        gate = "" if group is None else '    #[cfg(feature = "{}")]\n'.format(group)
        parts.append('{}    Label {{ text: "{}", encoding: &e::{}, whatwg: true }},\n'
                     .format(gate, label, const))
    parts.append("];\n\n")
    parts.append("/// Every encoding compiled in: the standard's first, then the rest.\n")
    parts.append("pub static ALL_ENCODINGS: &[&Encoding] = &[\n")
    for name in names:
        parts.append("    {}&e::{},\n".format(
            cfg(name).replace("\n", "\n    "), CONST_NAMES[name]))
    for group, _n, ident, _f, _cp, _l, _full in EXTRA:
        parts.append('    #[cfg(feature = "{}")]\n    &x::{}_INIT,\n'.format(group, ident))
    for group, _n, ident, _v, _cp, _l in ALGORITHMIC:
        gate = "" if group is None else '    #[cfg(feature = "{}")]\n'.format(group)
        parts.append('{}    &x::{}_INIT,\n'.format(gate, ident))
    parts.append("];\n")
    write(os.path.join(OUT, "labels.rs"), "".join(parts))

    # --- the Encoding constants and statics ------------------------------
    # Encoding name -> the table identifier in tables::single_byte.
    sb_tables = {n: CONST_NAMES[n][: -len("_INIT")]
                 for n in names if feature(n) == "single-byte"}
    # ISO-8859-8-I shares its index with ISO-8859-8.
    sb_tables["ISO-8859-8-I"] = "ISO_8859_8"
    parts = [HEADER, """
//! The [`Encoding`] instances for every encoding compiled in.
//!
//! Each exists once as a private `const`, so that it can be named in other
//! constants such as the label table, and once as the `&'static` reference the
//! API hands out.  Both are gated on the feature that carries the encoding's
//! tables; see the crate documentation for what each feature covers.

use crate::Encoding;
#[cfg(feature = "single-byte")]
use crate::tables::single_byte as sb;
use crate::variant::VariantEncoding;
"""]
    for group in encodings:
        parts.append("\n// {}\n".format(group["heading"]))
        for enc in group["encodings"]:
            name = enc["name"]
            const = CONST_NAMES[name]
            if name in sb_tables:
                t = sb_tables[name]
                variant = ("VariantEncoding::SingleByte(\n"
                           "    &sb::{t}_DECODE,\n"
                           "    &sb::{t}_ENCODE_CODE_POINTS,\n"
                           "    &sb::{t}_ENCODE_BYTES,\n)").format(t=t)
            else:
                variant = "VariantEncoding::" + VARIANTS[name]
            doc = ENCODING_DOCS.get(name, "{}.".format(name))
            gate = cfg(name)
            parts.append('\n{}pub(crate) const {}: Encoding = Encoding::new("{}", {});\n'
                         .format(gate, const, name, variant))
            parts.append('/// {}\n{}pub static {}: &Encoding = &{};\n'
                         .format(doc, gate, const[:-len("_INIT")], const))
    write(os.path.join(ROOT, "src", "encodings.rs"), "".join(parts))

    # --- transliteration -------------------------------------------------
    folds = build_translit()
    blob = ""
    spans = []
    for text in folds.values():
        at = blob.find(text)
        if at < 0:
            at = len(blob)
            blob += text
        spans.append((at, len(text)))
    assert len(blob) < 0x10000 and all(l < 256 for _, l in spans)
    parts = [HEADER, """
//! ASCII folds for transliteration.
//!
//! Derived from Unicode's own decompositions, with a table in the generator for
//! what does not decompose.  Keys are sorted for binary search; each span is an
//! offset and length into the one shared blob.

#[rustfmt::skip]
pub static KEYS: [u16; %d] = [
%s
];

#[rustfmt::skip]
pub static SPANS: [(u16, u8); %d] = [
%s
];

pub static DATA: &str = %s;
""" % (
        len(folds), rows(list(folds), 12, u16_hex),
        len(spans),
        "\n".join("    " + " ".join("(0x{:04X}, {}),".format(o, l) for o, l in spans[i:i + 8])
                   for i in range(0, len(spans), 8)),
        json.dumps(blob),
    )]
    write(os.path.join(OUT, "translit.rs"), "".join(parts))

    # --- module root -----------------------------------------------------
    write(os.path.join(OUT, "mod.rs"), HEADER + """
//! Static index tables derived from the WHATWG Encoding Standard.
//!
//! Each module is gated on the feature that asks for its encodings, so a build
//! that wants only, say, Shift_JIS carries none of the Chinese or Korean data.

#[cfg(feature = "big5")]
pub mod big5;
#[cfg(feature = "euc-kr")]
pub mod euc_kr;
#[cfg(feature = "gb18030")]
pub mod gb18030;
#[cfg(feature = "gb18030")]
pub mod gb2312;
#[cfg(any(feature = "euc-jp", feature = "iso-2022-jp", feature = "shift-jis"))]
pub mod jis;
#[cfg(any(\n    feature = "dos",\n    feature = "ebcdic",\n    feature = "mac",\n    feature = "misc",\n    feature = "single-byte"\n))]
pub mod extra;
pub mod extra_labels;
pub mod labels;
#[cfg(feature = "single-byte")]
pub mod single_byte;
#[cfg(feature = "translit")]
pub mod translit;
""")


if __name__ == "__main__":
    main()
