// @generated by tools/generate_tables.py from the WHATWG Encoding Standard indexes.
// https://encoding.spec.whatwg.org/indexes.json
// Do not edit by hand; re-run the generator instead.

//! The [`Encoding`] instances for the charsets outside the standard.

use crate::Encoding;
use crate::tables::extra as t;
use crate::variant::VariantEncoding;

// IBM PC / OEM code pages

#[cfg(feature = "dos")]
pub(crate) const IBM437_INIT: Encoding = Encoding::new(
    "IBM437",
    VariantEncoding::SingleByte(
        &t::IBM437_DECODE,
        &t::IBM437_ENCODE_CODE_POINTS,
        &t::IBM437_ENCODE_BYTES,
    ),
);
/// IBM437
#[cfg(feature = "dos")]
pub static IBM437: &Encoding = &IBM437_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM737_INIT: Encoding = Encoding::new(
    "IBM737",
    VariantEncoding::SingleByte(
        &t::IBM737_DECODE,
        &t::IBM737_ENCODE_CODE_POINTS,
        &t::IBM737_ENCODE_BYTES,
    ),
);
/// IBM737
#[cfg(feature = "dos")]
pub static IBM737: &Encoding = &IBM737_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM775_INIT: Encoding = Encoding::new(
    "IBM775",
    VariantEncoding::SingleByte(
        &t::IBM775_DECODE,
        &t::IBM775_ENCODE_CODE_POINTS,
        &t::IBM775_ENCODE_BYTES,
    ),
);
/// IBM775
#[cfg(feature = "dos")]
pub static IBM775: &Encoding = &IBM775_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM850_INIT: Encoding = Encoding::new(
    "IBM850",
    VariantEncoding::SingleByte(
        &t::IBM850_DECODE,
        &t::IBM850_ENCODE_CODE_POINTS,
        &t::IBM850_ENCODE_BYTES,
    ),
);
/// IBM850
#[cfg(feature = "dos")]
pub static IBM850: &Encoding = &IBM850_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM852_INIT: Encoding = Encoding::new(
    "IBM852",
    VariantEncoding::SingleByte(
        &t::IBM852_DECODE,
        &t::IBM852_ENCODE_CODE_POINTS,
        &t::IBM852_ENCODE_BYTES,
    ),
);
/// IBM852
#[cfg(feature = "dos")]
pub static IBM852: &Encoding = &IBM852_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM855_INIT: Encoding = Encoding::new(
    "IBM855",
    VariantEncoding::SingleByte(
        &t::IBM855_DECODE,
        &t::IBM855_ENCODE_CODE_POINTS,
        &t::IBM855_ENCODE_BYTES,
    ),
);
/// IBM855
#[cfg(feature = "dos")]
pub static IBM855: &Encoding = &IBM855_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM856_INIT: Encoding = Encoding::new(
    "IBM856",
    VariantEncoding::SingleByte(
        &t::IBM856_DECODE,
        &t::IBM856_ENCODE_CODE_POINTS,
        &t::IBM856_ENCODE_BYTES,
    ),
);
/// IBM856
#[cfg(feature = "dos")]
pub static IBM856: &Encoding = &IBM856_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM857_INIT: Encoding = Encoding::new(
    "IBM857",
    VariantEncoding::SingleByte(
        &t::IBM857_DECODE,
        &t::IBM857_ENCODE_CODE_POINTS,
        &t::IBM857_ENCODE_BYTES,
    ),
);
/// IBM857
#[cfg(feature = "dos")]
pub static IBM857: &Encoding = &IBM857_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM860_INIT: Encoding = Encoding::new(
    "IBM860",
    VariantEncoding::SingleByte(
        &t::IBM860_DECODE,
        &t::IBM860_ENCODE_CODE_POINTS,
        &t::IBM860_ENCODE_BYTES,
    ),
);
/// IBM860
#[cfg(feature = "dos")]
pub static IBM860: &Encoding = &IBM860_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM861_INIT: Encoding = Encoding::new(
    "IBM861",
    VariantEncoding::SingleByte(
        &t::IBM861_DECODE,
        &t::IBM861_ENCODE_CODE_POINTS,
        &t::IBM861_ENCODE_BYTES,
    ),
);
/// IBM861
#[cfg(feature = "dos")]
pub static IBM861: &Encoding = &IBM861_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM862_INIT: Encoding = Encoding::new(
    "IBM862",
    VariantEncoding::SingleByte(
        &t::IBM862_DECODE,
        &t::IBM862_ENCODE_CODE_POINTS,
        &t::IBM862_ENCODE_BYTES,
    ),
);
/// IBM862
#[cfg(feature = "dos")]
pub static IBM862: &Encoding = &IBM862_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM863_INIT: Encoding = Encoding::new(
    "IBM863",
    VariantEncoding::SingleByte(
        &t::IBM863_DECODE,
        &t::IBM863_ENCODE_CODE_POINTS,
        &t::IBM863_ENCODE_BYTES,
    ),
);
/// IBM863
#[cfg(feature = "dos")]
pub static IBM863: &Encoding = &IBM863_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM864_INIT: Encoding = Encoding::new(
    "IBM864",
    VariantEncoding::FullByte(
        &t::IBM864_DECODE,
        &t::IBM864_ENCODE_CODE_POINTS,
        &t::IBM864_ENCODE_BYTES,
    ),
);
/// IBM864
#[cfg(feature = "dos")]
pub static IBM864: &Encoding = &IBM864_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM865_INIT: Encoding = Encoding::new(
    "IBM865",
    VariantEncoding::SingleByte(
        &t::IBM865_DECODE,
        &t::IBM865_ENCODE_CODE_POINTS,
        &t::IBM865_ENCODE_BYTES,
    ),
);
/// IBM865
#[cfg(feature = "dos")]
pub static IBM865: &Encoding = &IBM865_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM869_INIT: Encoding = Encoding::new(
    "IBM869",
    VariantEncoding::SingleByte(
        &t::IBM869_DECODE,
        &t::IBM869_ENCODE_CODE_POINTS,
        &t::IBM869_ENCODE_BYTES,
    ),
);
/// IBM869
#[cfg(feature = "dos")]
pub static IBM869: &Encoding = &IBM869_INIT;

#[cfg(feature = "dos")]
pub(crate) const IBM1006_INIT: Encoding = Encoding::new(
    "IBM1006",
    VariantEncoding::SingleByte(
        &t::IBM1006_DECODE,
        &t::IBM1006_ENCODE_CODE_POINTS,
        &t::IBM1006_ENCODE_BYTES,
    ),
);
/// IBM1006
#[cfg(feature = "dos")]
pub static IBM1006: &Encoding = &IBM1006_INIT;

// IBM mainframe EBCDIC code pages

#[cfg(feature = "ebcdic")]
pub(crate) const IBM037_INIT: Encoding = Encoding::new(
    "IBM037",
    VariantEncoding::FullByte(
        &t::IBM037_DECODE,
        &t::IBM037_ENCODE_CODE_POINTS,
        &t::IBM037_ENCODE_BYTES,
    ),
);
/// IBM037
#[cfg(feature = "ebcdic")]
pub static IBM037: &Encoding = &IBM037_INIT;

#[cfg(feature = "ebcdic")]
pub(crate) const IBM424_INIT: Encoding = Encoding::new(
    "IBM424",
    VariantEncoding::FullByte(
        &t::IBM424_DECODE,
        &t::IBM424_ENCODE_CODE_POINTS,
        &t::IBM424_ENCODE_BYTES,
    ),
);
/// IBM424
#[cfg(feature = "ebcdic")]
pub static IBM424: &Encoding = &IBM424_INIT;

#[cfg(feature = "ebcdic")]
pub(crate) const IBM500_INIT: Encoding = Encoding::new(
    "IBM500",
    VariantEncoding::FullByte(
        &t::IBM500_DECODE,
        &t::IBM500_ENCODE_CODE_POINTS,
        &t::IBM500_ENCODE_BYTES,
    ),
);
/// IBM500
#[cfg(feature = "ebcdic")]
pub static IBM500: &Encoding = &IBM500_INIT;

#[cfg(feature = "ebcdic")]
pub(crate) const IBM875_INIT: Encoding = Encoding::new(
    "IBM875",
    VariantEncoding::FullByte(
        &t::IBM875_DECODE,
        &t::IBM875_ENCODE_CODE_POINTS,
        &t::IBM875_ENCODE_BYTES,
    ),
);
/// IBM875
#[cfg(feature = "ebcdic")]
pub static IBM875: &Encoding = &IBM875_INIT;

#[cfg(feature = "ebcdic")]
pub(crate) const IBM1026_INIT: Encoding = Encoding::new(
    "IBM1026",
    VariantEncoding::FullByte(
        &t::IBM1026_DECODE,
        &t::IBM1026_ENCODE_CODE_POINTS,
        &t::IBM1026_ENCODE_BYTES,
    ),
);
/// IBM1026
#[cfg(feature = "ebcdic")]
pub static IBM1026: &Encoding = &IBM1026_INIT;

// Apple's regional variants of Mac OS Roman

#[cfg(feature = "mac")]
pub(crate) const X_MAC_ARABIC_INIT: Encoding = Encoding::new(
    "x-mac-arabic",
    VariantEncoding::SingleByte(
        &t::X_MAC_ARABIC_DECODE,
        &t::X_MAC_ARABIC_ENCODE_CODE_POINTS,
        &t::X_MAC_ARABIC_ENCODE_BYTES,
    ),
);
/// x-mac-arabic
#[cfg(feature = "mac")]
pub static X_MAC_ARABIC: &Encoding = &X_MAC_ARABIC_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_CELTIC_INIT: Encoding = Encoding::new(
    "x-mac-celtic",
    VariantEncoding::SingleByte(
        &t::X_MAC_CELTIC_DECODE,
        &t::X_MAC_CELTIC_ENCODE_CODE_POINTS,
        &t::X_MAC_CELTIC_ENCODE_BYTES,
    ),
);
/// x-mac-celtic
#[cfg(feature = "mac")]
pub static X_MAC_CELTIC: &Encoding = &X_MAC_CELTIC_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_CENTRALEURROMAN_INIT: Encoding = Encoding::new(
    "x-mac-centraleurroman",
    VariantEncoding::SingleByte(
        &t::X_MAC_CENTRALEURROMAN_DECODE,
        &t::X_MAC_CENTRALEURROMAN_ENCODE_CODE_POINTS,
        &t::X_MAC_CENTRALEURROMAN_ENCODE_BYTES,
    ),
);
/// x-mac-centraleurroman
#[cfg(feature = "mac")]
pub static X_MAC_CENTRALEURROMAN: &Encoding = &X_MAC_CENTRALEURROMAN_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_CROATIAN_INIT: Encoding = Encoding::new(
    "x-mac-croatian",
    VariantEncoding::SingleByte(
        &t::X_MAC_CROATIAN_DECODE,
        &t::X_MAC_CROATIAN_ENCODE_CODE_POINTS,
        &t::X_MAC_CROATIAN_ENCODE_BYTES,
    ),
);
/// x-mac-croatian
#[cfg(feature = "mac")]
pub static X_MAC_CROATIAN: &Encoding = &X_MAC_CROATIAN_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_FARSI_INIT: Encoding = Encoding::new(
    "x-mac-farsi",
    VariantEncoding::SingleByte(
        &t::X_MAC_FARSI_DECODE,
        &t::X_MAC_FARSI_ENCODE_CODE_POINTS,
        &t::X_MAC_FARSI_ENCODE_BYTES,
    ),
);
/// x-mac-farsi
#[cfg(feature = "mac")]
pub static X_MAC_FARSI: &Encoding = &X_MAC_FARSI_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_GAELIC_INIT: Encoding = Encoding::new(
    "x-mac-gaelic",
    VariantEncoding::SingleByte(
        &t::X_MAC_GAELIC_DECODE,
        &t::X_MAC_GAELIC_ENCODE_CODE_POINTS,
        &t::X_MAC_GAELIC_ENCODE_BYTES,
    ),
);
/// x-mac-gaelic
#[cfg(feature = "mac")]
pub static X_MAC_GAELIC: &Encoding = &X_MAC_GAELIC_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_GREEK_INIT: Encoding = Encoding::new(
    "x-mac-greek",
    VariantEncoding::SingleByte(
        &t::X_MAC_GREEK_DECODE,
        &t::X_MAC_GREEK_ENCODE_CODE_POINTS,
        &t::X_MAC_GREEK_ENCODE_BYTES,
    ),
);
/// x-mac-greek
#[cfg(feature = "mac")]
pub static X_MAC_GREEK: &Encoding = &X_MAC_GREEK_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_ICELANDIC_INIT: Encoding = Encoding::new(
    "x-mac-icelandic",
    VariantEncoding::SingleByte(
        &t::X_MAC_ICELANDIC_DECODE,
        &t::X_MAC_ICELANDIC_ENCODE_CODE_POINTS,
        &t::X_MAC_ICELANDIC_ENCODE_BYTES,
    ),
);
/// x-mac-icelandic
#[cfg(feature = "mac")]
pub static X_MAC_ICELANDIC: &Encoding = &X_MAC_ICELANDIC_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_ROMANIAN_INIT: Encoding = Encoding::new(
    "x-mac-romanian",
    VariantEncoding::SingleByte(
        &t::X_MAC_ROMANIAN_DECODE,
        &t::X_MAC_ROMANIAN_ENCODE_CODE_POINTS,
        &t::X_MAC_ROMANIAN_ENCODE_BYTES,
    ),
);
/// x-mac-romanian
#[cfg(feature = "mac")]
pub static X_MAC_ROMANIAN: &Encoding = &X_MAC_ROMANIAN_INIT;

#[cfg(feature = "mac")]
pub(crate) const X_MAC_TURKISH_INIT: Encoding = Encoding::new(
    "x-mac-turkish",
    VariantEncoding::SingleByte(
        &t::X_MAC_TURKISH_DECODE,
        &t::X_MAC_TURKISH_ENCODE_CODE_POINTS,
        &t::X_MAC_TURKISH_ENCODE_BYTES,
    ),
);
/// x-mac-turkish
#[cfg(feature = "mac")]
pub static X_MAC_TURKISH: &Encoding = &X_MAC_TURKISH_INIT;

// Everything else

#[cfg(feature = "misc")]
pub(crate) const ATARI_ST_INIT: Encoding = Encoding::new(
    "Atari-ST",
    VariantEncoding::SingleByte(
        &t::ATARI_ST_DECODE,
        &t::ATARI_ST_ENCODE_CODE_POINTS,
        &t::ATARI_ST_ENCODE_BYTES,
    ),
);
/// Atari-ST
#[cfg(feature = "misc")]
pub static ATARI_ST: &Encoding = &ATARI_ST_INIT;

#[cfg(feature = "misc")]
pub(crate) const KZ_1048_INIT: Encoding = Encoding::new(
    "KZ-1048",
    VariantEncoding::SingleByte(
        &t::KZ_1048_DECODE,
        &t::KZ_1048_ENCODE_CODE_POINTS,
        &t::KZ_1048_ENCODE_BYTES,
    ),
);
/// KZ-1048
#[cfg(feature = "misc")]
pub static KZ_1048: &Encoding = &KZ_1048_INIT;
